designer/server/src/common/templates/layouts/page.njk
Unlike the other assets, these two are webpack entries
=> Fix paths to fingerprinted CSS and JS

.github/dependabot.yml
Development tools have been grouped to reduce the number of PRs
=> Add Dependabot updates

designer/client/src/javascripts/application.js, designer/client/src/stylesheets/components/_all.scss, designer/server/src/common/components/service-header/_service-header.scss, designer/server/src/common/components/service-header/macro.njk, designer/server/src/common/components/service-header/service-header.js, designer/server/src/common/components/service-header/template.njk, designer/server/src/common/nunjucks/context/index.js, designer/server/src/common/templates/layouts/page.njk, designer/server/src/common/templates/partials/navigation.njk, designer/server/src/createServer-healthcheck.test.ts, designer/server/src/createServer.test.ts, designer/server/src/views/help/cookies.njk, designer/server/src/views/help/feedback.njk, designer/server/src/views/home.njk
This PR adds a customised version of the One Login header including:
1. User display name in header
2. Beta phase banner
3. Feedback form page
=> Add service navigation header, phase banner

designer/client/src/api/designerApi.ts, designer/client/src/api/toggleApi.test.tsx, designer/client/src/api/toggleApi.ts, designer/client/src/components/Visualisation/visualisation.scss, designer/client/src/index.tsx, designer/client/src/plugins/logger.ts, designer/client/src/stylesheets/application.scss, designer/client/src/stylesheets/editor.scss, designer/server/src/common/helpers/auth/azure-oidc.js, designer/server/src/common/nunjucks/context/build-navigation.js, designer/server/src/common/nunjucks/context/build-navigation.test.js, designer/server/src/common/nunjucks/context/index.js, designer/server/src/common/templates/layouts/page.njk, designer/server/src/common/templates/partials/navigation.njk, designer/server/src/config.ts, designer/server/src/createServer-healthcheck.test.ts, designer/server/src/createServer.test.ts, designer/server/src/createServer.ts, designer/server/src/models/library.js, designer/server/src/plugins/routes/api.test.js, designer/server/src/plugins/routes/app.test.js, designer/server/src/routes/auth.js, designer/server/src/routes/library.test.js, designer/server/src/routes/login.js, designer/server/src/views/help/cookies.njk, designer/server/src/views/help/feedback.njk, designer/server/src/views/home.njk, designer/webpack.config.cjs
https://dev.azure.com/defragovuk/DEFRA-CDP/_workitems/edit/362001
Removed the mount path capability `appPathPrefix`.
=> Remove appPathPrefix

designer/server/src/routes/forms/create.js
Another PR will update the API client to actually hit **forms-manager**
=> Submit to API client when form metadata is valid

designer/server/src/lib/fetch.js, designer/server/src/lib/forms.js
1. Updates form API client to use URL (not string) types
2. Wires up create/update API calls
=> Wire up create/update API calls

.eslintrc.cjs, designer/client/src/components/FieldEditors/date-field-edit.test.tsx, designer/client/src/components/FieldEditors/number-field-edit.test.tsx, designer/client/src/components/FieldEditors/text-field-edit.test.tsx, designer/client/src/components/Visualisation/Visualisation.test.tsx, designer/client/src/conditions/ConditionsEdit.test.tsx, designer/client/src/conditions/inline-condition-helpers.test.ts, designer/client/src/data/page/findPage.ts
Copying a few bits from the other `@defra/forms-*` repos
=> Update ESLint rules with plugin recommendations etc

designer/server/src/common/nunjucks/filters/format-date.js, designer/server/src/common/nunjucks/filters/format-date.test.js, designer/server/src/models/forms/library.js, designer/server/src/views/forms/library.njk
Where available, dummy data will now be replaced by actual form JSON
```js
form.draft.updatedAt
form.draft.updatedBy
```
=> Update forms library to use form API "updated" dates etc

designer/server/src/routes/forms/create.js, model/package.json, model/src/form/form-metadata/index.ts, model/src/utils/helpers.test.js, model/src/utils/helpers.ts, package-lock.json, package.json
Addresses code review feedback from https://github.com/DEFRA/forms-designer/pull/147/files#r1597036098
=> Move slug formatting to `slugify` helper

designer/server/src/lib/forms.js, designer/server/src/routes/forms/create.js
Split out from https://github.com/DEFRA/forms-designer/pull/150 as discussed with @davidjamesstone
=> Add helper `getAuthor()` to check credentials

designer/client/src/components/Flyout/Flyout.tsx, designer/client/src/components/Page/Page.tsx, designer/client/src/components/Visualisation/Visualisation.tsx, designer/server/src/routes/forms/create.js
This PR adds missing types and switches page preview URLs from `id` to `slug`
=> Use slug for page preview URL and create form redirect

designer/server/src/common/helpers/auth/get-user-session.js, designer/server/src/common/helpers/auth/user-session.js
This PR updates our `getUserClaims()` helper to add the decoded ID token
=> Decode ID token via `getUserClaims()`

designer/server/src/common/helpers/auth/azure-oidc.js, designer/server/src/common/helpers/auth/user-session.js, designer/server/src/routes/account/sign-out.js, designer/server/src/routes/account/signed-out.js, designer/server/src/views/account/signed-out.njk
This PR ensures we redirect to the "Signed out" page after signing out
I've added `id_token_hint` to sign out a specific account but this has no effect for `@defradev.onmicrosoft.com`
=> Add sign out redirect URL

.github/workflows/check-pull-request.yml, designer/client/src/javascripts/application.js, designer/client/src/stylesheets/components/_all.scss, designer/package.json, designer/server/src/views/forms/editor.njk, designer/webpack.config.js, package-lock.json
Some quick config changes in preparation for GOV.UK Frontend v5
=> Configure webpack to output ES modules

designer/client/src/component.js, designer/client/src/components/Visualisation/visualisation.scss, designer/client/src/stylesheets/editor.scss
It's now possible to tab through the form editor
=> Add missing keyboard focus styles

designer/server/src/routes/forms/api.js
E.g. When saving legacy form JSON with payment options
=> Strip unknown JSON fields on editor PUT

designer/server/src/common/helpers/auth/azure-oidc.js, designer/server/src/common/helpers/auth/get-user-session.js, designer/server/src/common/helpers/auth/refresh-token.js, designer/server/src/common/helpers/auth/session-cookie.js, designer/server/src/common/helpers/auth/user-session.js
This PR restores support for refresh tokens
=> Extend expired sessions using refresh token

designer/client/src/DeclarationEdit.tsx, designer/client/src/Editor.tsx, designer/client/src/ErrorSummary.tsx, designer/client/src/PageCreate.tsx, designer/client/src/PageEdit.tsx, designer/client/src/components/FieldEditors/ParaEdit.tsx, designer/client/src/hooks/list/useListItem/useListItem.tsx, designer/client/src/i18n/i18n.tsx, designer/client/src/index.tsx, designer/client/src/list/ListEdit.tsx, designer/client/src/outputs/OutputEdit.tsx, designer/client/src/outputs/types.ts, designer/client/src/reducers/component/componentReducer.validations.ts, designer/client/src/section/SectionEdit.tsx, designer/client/src/validations.ts
Lots of UI fixes for form designer error messages and form validation
=> Fixes for error messages

designer/client/src/LinkCreate.test.tsx, designer/client/src/conditions/InlineConditionsDefinitionValue.test.tsx, designer/client/src/conditions/select-condition-helpers.test.ts, designer/client/src/list/ListEdit.tsx, designer/client/src/reducers/listReducer.tsx, model/src/components/component-types.ts, model/src/components/index.ts, model/src/components/types.ts, model/src/conditions/condition-field.ts, model/src/conditions/condition-model.test.ts, model/src/conditions/condition-operators.ts, model/src/conditions/condition-ref.ts, model/src/conditions/condition-values.test.ts, model/src/conditions/condition-values.ts, model/src/conditions/condition.ts, model/src/conditions/enums.ts, model/src/conditions/index.ts, model/src/conditions/types.ts, model/tsconfig.build.json, tsconfig.base.json
This PR sets up types and enums for "Conditional components"
=> Add types and enums for conditions and operators

designer/client/src/Designer.tsx, designer/client/src/components/Menu/Menu.test.tsx, designer/client/src/components/Menu/Menu.tsx, designer/client/src/components/Menu/SubMenu.tsx
This PR clears the file upload input after it completes, ready for the next upload
I've also included:
1. JSON is formatted via **Download form** for readability
2. JSON files saved as ~`${id}.json`~ `${slug}.json` for readability
3. Logger added for errors
4. ESLint issues fixes
=> Fix issue preventing subsequent file uploads

designer/client/src/components/Menu/SubMenu.tsx
This PR logs "Upload file contents invalid" separately to "Upload file failed"
=> Add logging for file upload JSON parsing

designer/client/src/PageCreate.tsx, designer/client/src/PageEdit.tsx, designer/client/src/section/SectionEdit.tsx, designer/client/src/section/SectionsEdit.tsx
This PR adds consistent props + types to `<SectionEdit>` and guards edits to sections when `undefined`
=> Guard against unmatched section issues

model/src/components/component-types.ts
This PR completes the **forms-designer** changes for [story #366938](https://dev.azure.com/defragovuk/DEFRA-CDP/_workitems/edit/366938)
=> Add default hint text to email address component

designer/client/src/Component.tsx, designer/client/src/LinkEdit.tsx, designer/client/src/components/Page/Page.tsx, model/src/form/form-definition/index.ts, model/src/form/form-definition/types.ts
These were starting to get in the way whilst unpicking conditions etc
Part of story [#411568](https://dev.azure.com/defragovuk/DEFRA-CDP/_boards/board/t/DXT%20Team/Stories?System.IterationPath=%40currentIteration&workitem=411568)
=> Remove unused `RepeatingFieldPage` and related types

model/src/form/form-metadata/index.ts
https://dev.azure.com/defragovuk/DEFRA-CDP/_workitems/edit/401088
=> refactor: formMetadataInput for reuse as optional or required [401088]

designer/client/src/Component.tsx, designer/client/src/components/Page/Page.tsx, designer/client/src/i18n/translations/en.translation.json, designer/client/src/stylesheets/editor.scss
WIP.
Dan S is happy with this approach but there's some accessibilty imrpovements with the show/hide to be made.
=> 392202 - Reorder components

model/src/form/form-definition/index.ts
https://dev.azure.com/defragovuk/DEFRA-CDP/_workitems/edit/416324
=> Ensure schema coerces minDaysInFuture and maxDaysInFuture to numbers (416324)

designer/server/src/models/forms/create.js, designer/server/src/models/forms/edit.js, designer/server/src/models/forms/edit.test.js, designer/server/src/routes/forms/edit.js, designer/server/src/routes/forms/edit.test.js, designer/server/src/views/forms/overview.njk, designer/server/test/helpers/component-helpers.js
https://dev.azure.com/defragovuk/DEFRA-CDP/_workitems/edit/401106
https://dev.azure.com/defragovuk/DEFRA-CDP/_workitems/edit/401107
**BEFORE:**
**MAKE CHANGE**
**CHANGE CONFIRMATION**
=> feat: [401106, 401107] Amend team name and email

designer/server/src/index.ts, designer/server/src/server.ts
No rush for this one, just spotted we don't have the "Server started successfully" message etc
=> Add standard logging to start script

designer/server/src/models/forms/edit.test.js
Tiny fix from https://github.com/DEFRA/forms-designer/pull/363
=> Fix invalid type suggestion

designer/client/src/ComponentTypeEdit.test.tsx, designer/client/src/LinkCreate.test.tsx, designer/client/src/PageCreate.tsx, designer/client/src/PageEdit.tsx, designer/client/src/data/page/updateLinksTo.test.ts, designer/client/src/helpers.js, designer/client/src/helpers.test.tsx, designer/client/src/i18n/translations/en.translation.json, designer/server/src/createServer.ts, designer/server/src/routes/forms/api.test.js, model/src/form/utils/update-start-page.test.ts
Fixes issues found in https://github.com/DEFRA/forms-runner/pull/332
Good to address this before adding more controllers (e.g. file upload)
=> Avoid legacy controller paths in form JSON

designer/server/src/lib/file.js, designer/server/src/plugins/errorPage.ts, designer/server/src/routes/file/file.js, designer/server/src/views/403.njk, designer/server/src/views/404.njk, designer/server/src/views/500.njk
- Remove logging of an email address
- Handle 404, 500 errors from forms-submission-api
- Fix an incorrect mailto link in the 403 page
=> Download page improvements

designer/server/src/models/forms/privacy-notice.js, designer/server/src/models/forms/privacy-notice.test.js, designer/server/src/routes/forms/index.js, designer/server/src/routes/forms/library.js, designer/server/src/routes/forms/privacy-notice.js, designer/server/src/routes/forms/privacy-notice.test.js, designer/server/src/views/forms/overview.njk, designer/server/src/views/forms/privacy-notice.njk, model/src/form/form-metadata/index.ts, model/src/form/form-metadata/types.ts
=> Edit privacy notice url in form metadata

sonar-project.properties
I've added a Sonar project config to try and limit issues flagged in test files
=> Add Sonar project config

designer/server/src/views/forms/partials/overview-live.njk
Update timestamps on the live overview summary
=> Update Form Overview Page for Live Forms

designer/client/src/stylesheets/editor.scss
This PR is in preparation for [story #427243](https://dev.azure.com/defragovuk/DEFRA-CDP/_workitems/edit/427243)
Component up/down button alignment issues are now resolved
I've also reviewed keyboard focus styles when moving focus to the up/down buttons
https://github.com/user-attachments/assets/1cb508cc-10f1-4ef7-8dbc-03ced05bb1a7
=> Fix up/down arrow alignment on small screens + focus

designer/client/src/Component.tsx, designer/client/src/SortUpDown.tsx, designer/client/src/components/Flyout/Flyout.scss, designer/client/src/components/Page/Page.tsx, designer/client/src/data/component/updateComponents.test.ts, designer/client/src/data/component/updateComponents.ts, designer/client/src/helpers.js, designer/client/src/helpers.test.js, designer/client/src/stylesheets/editor-colours.scss, designer/client/src/stylesheets/editor.scss, designer/client/src/stylesheets/variables/_colours.scss
This PR splits out up/down sorting into a new `<SortUpDown>` component
I've added test coverage for the `arrayMove()` helper and split out helper code ready for list sorting
=> Split out up/down sorting

designer/client/src/Component.tsx, designer/client/src/SortUpDown.tsx, designer/client/src/components/Flyout/Flyout.scss, designer/client/src/hooks/list/useListItem/types.ts, designer/client/src/hooks/list/useListItem/useListItem.tsx, designer/client/src/i18n/translations/en.translation.json, designer/client/src/list/ListEdit.tsx, designer/client/src/list/ListItemEdit.tsx, designer/client/src/list/ListItems.tsx, designer/client/src/stylesheets/editor.scss
This PR adds list item up/down sorting for [story #427243](https://dev.azure.com/defragovuk/DEFRA-CDP/_workitems/edit/427243)
=> Enable list item up/down sorting

.github/workflows/check-pull-request.yml, jest.config.js, sonar-project.properties
As shown on the **Administration** → **Analysis Method** page
I've also tried adding `sonar.cpd.exclusions` to exclude tests from duplicate code checks
=> Run Sonar via GitHub Actions

designer/client/src/PageEdit.test.tsx, designer/client/src/PageEdit.tsx, designer/client/src/components/ComponentCreate/ComponentCreateList.test.tsx, designer/client/src/components/ComponentCreate/ComponentCreateList.tsx, designer/client/src/components/Page/Page.tsx, designer/client/src/components/Visualisation/visualisation.scss, designer/client/src/data/component/fields.ts, designer/client/src/helpers.js, designer/client/src/i18n/translations/en.translation.json, model/src/form/form-definition/index.ts, model/src/form/form-definition/types.ts, model/src/pages/controller-types.ts, model/src/pages/enums.ts, model/src/pages/helpers.ts, model/src/pages/index.ts, model/src/pages/page-types.ts
=> feature/300773 -  Add another

designer/server/src/common/helpers/auth/session-cookie.js, designer/server/src/createServer.ts
Fixes [bug #474752](https://dev.azure.com/defragovuk/DEFRA-CDP/_workitems/edit/474752)
=> Turn off Hapi `strictHeader` and clear invalid session cookies

designer/server/src/routes/account/sign-out.js
Fixes [bug #417348](https://dev.azure.com/defragovuk/DEFRA-CDP/_workitems/edit/417348)
=> Remove optional `id_token_hint` to prevent sign out error

designer/client/src/Designer.tsx, designer/client/src/stylesheets/components/_visualisation.scss, designer/client/src/stylesheets/partials/_grid.scss, designer/server/src/common/components/masthead/template.njk, designer/server/src/common/components/page-body/macro.njk, designer/server/src/common/components/service-header/template.njk, designer/server/src/common/templates/layouts/page.njk, designer/server/src/common/templates/partials/navigation.njk, designer/server/src/views/forms/contact/email.njk, designer/server/src/views/forms/contact/online.njk, designer/server/src/views/forms/contact/phone.njk, designer/server/src/views/forms/editor.njk, designer/server/src/views/forms/notification-email.njk, designer/server/src/views/forms/overview.njk, designer/server/src/views/forms/privacy-notice.njk, designer/server/src/views/forms/question-input.njk, designer/server/src/views/forms/question-inputs.njk, designer/server/src/views/forms/question-radios.njk, designer/server/src/views/forms/submission-guidance.njk
Probably should have added this to https://github.com/DEFRA/forms-designer/pull/660 as part of [story #488717](https://dev.azure.com/defragovuk/DEFRA-CDP/_workitems/edit/488717)
=> New designer: Switch to wider 1300px layout

designer/server/src/routes/forms/library.test.js, model/src/common/search/index.ts, model/src/common/search/types.ts, model/src/common/types.ts
https://dev.azure.com/defragovuk/DEFRA-CDP/_workitems/edit/479076
This PR introduces the types and schema changes for the upcoming advanced search and filtering feature
=> Feature 479076: Types and schema for advanced search and filtering

designer/server/src/views/forms/overview.njk, designer/server/src/views/forms/partials/overview-draft.njk, designer/server/src/views/forms/partials/overview-live.njk, model/src/utils/markdown.ts
https://dev.azure.com/defragovuk/DEFRA-CDP/_workitems/edit/494884
Example:
=> Chore 494884: Escape html

designer/client/src/conditions/SelectConditions.tsx
Fix binding of option in conditions selector
https://dev.azure.com/defragovuk/DEFRA-CDP/_workitems/edit/509850
=> Change when componentDidUpdate should update state in SelectConditions

model/src/form/form-definition/index.test.ts, model/src/form/form-definition/index.ts, model/src/form/form-definition/types.ts
Updating the Joi schema so we can add a uuid to pages
=> feat(model): 466796 - Add optional id to page schema

model/src/components/types.ts, model/src/form/form-definition/index.test.ts, model/src/form/form-definition/index.ts
Another one, adding id to questions (components) now.
=> feat(model): 466796 - Add add to component schema

designer/server/src/__stubs__/form-definition.js, designer/server/src/common/components/page-body/macro.njk, designer/server/src/common/components/page-panel-left/template.njk, designer/server/src/lib/editor.js, designer/server/src/lib/editor.test.js, designer/server/src/lib/error-helper.js, designer/server/src/models/forms/editor-v2/common.js, designer/server/src/models/forms/editor-v2/common.test.js, designer/server/src/models/forms/editor-v2/pages.js, designer/server/src/models/forms/editor-v2/question-details.js, designer/server/src/models/forms/editor-v2/question-type.js, designer/server/src/models/forms/editor-v2/questions.js, designer/server/src/routes/forms/editor-v2/helper.js, designer/server/src/routes/forms/editor-v2/helper.test.js, designer/server/src/routes/forms/editor-v2/page.js, designer/server/src/routes/forms/editor-v2/page.test.js, designer/server/src/routes/forms/editor-v2/question-details.js, designer/server/src/routes/forms/editor-v2/question-details.test.js, designer/server/src/routes/forms/editor-v2/question-type.js, designer/server/src/routes/forms/editor-v2/question-type.test.js, designer/server/src/routes/forms/editor-v2/questions.js, designer/server/src/routes/forms/editor-v2/questions.test.js, designer/server/src/typings/hapi/index.d.ts, designer/server/src/views/forms/editor-v2/pages.njk, designer/server/src/views/forms/editor-v2/partials/question-details-base.njk, designer/server/src/views/forms/editor-v2/question-details.njk, designer/server/src/views/forms/editor-v2/questions.njk, model/src/form/form-editor/index.ts, model/src/form/form-editor/types.ts
Allows a user to edit a page
Allows a user to edit a question
Allows a user to add an additional question
Eliminated all lint warnings on new code
Allows a user to preview a page or a form
Added no-visited-state class to action links
=> 466796 enhancements and 468287 implementation

designer/server/src/common/constants/editor.js, designer/server/src/models/forms/editor-v2/pages.js, designer/server/src/models/forms/editor-v2/pages.test.js, designer/server/src/models/forms/editor-v2/question-details.js, designer/server/src/models/forms/editor-v2/questions.js, designer/server/src/views/forms/editor-v2/question-details.njk, package-lock.json
Added 'change' link for changing question type
=> Added 'change' link for changing question type

model/src/form/form-definition/index.test.ts, model/src/form/form-definition/index.ts, model/src/form/form-definition/types.ts
Adding id to the list schema, with a default for the migration.
=> feat: 481476 - Add ids to List with default

designer/server/src/models/forms/editor-v2/guidance.js
Fixed guidance page (previously throwing an error due to a lint correction that had a knock-on)
=> Fixed guidance page

designer/server/src/common/constants/editor.js, designer/server/src/models/forms/editor-v2/question-type.js, designer/server/src/routes/forms/editor-v2/question-type.js, designer/server/src/routes/forms/editor-v2/question-type.test.js, designer/server/src/views/forms/editor-v2/partials/question-type.njk, model/src/form/form-editor/index.ts, model/src/form/form-editor/types.ts
Added sub-options radios for list type in question-type screen
=> Add list group sub-types

designer/client/src/i18n/i18n.tsx, designer/server/src/__stubs__/form-definition.js, designer/server/src/common/constants/editor.js, designer/server/src/models/forms/editor-v2/advanced-settings-fields.js, designer/server/src/models/forms/editor-v2/base-settings-fields.js, designer/server/src/models/forms/editor-v2/base-settings-fields.test.js, designer/server/src/models/forms/editor-v2/page-fields.js, designer/server/src/models/forms/editor-v2/page-fields.test.js, designer/server/src/models/forms/editor-v2/question-details.js, designer/server/src/models/forms/editor-v2/question-details.test.js, designer/server/src/plugins/errorPage.ts, designer/server/src/routes/forms/create.js, designer/server/src/routes/forms/editor-v2/question-details.test.js, designer/server/src/views/forms/editor-v2/partials/file-types.njk, designer/server/src/views/forms/editor-v2/partials/question-details-base.njk
This is a refactor to support addition of autocomplete question and additional base fields.
=> Refactor/481476  autocomplete question

designer/server/src/common/helpers/build-error-details.js, designer/server/src/common/helpers/build-error-details.test.js, designer/server/src/lib/error-helper.js, designer/server/src/lib/redirect-helper.js, designer/server/src/models/forms/editor-v2/base-settings-fields.js, designer/server/src/models/forms/editor-v2/question-details.js, designer/server/src/models/forms/editor-v2/question-details.test.js, designer/server/src/routes/forms/editor-v2/question-details-helper.js, designer/server/src/routes/forms/editor-v2/question-details-helper.test.js, designer/server/src/routes/forms/editor-v2/question-details.js, designer/server/src/routes/forms/editor-v2/question-details.test.js, designer/server/src/views/forms/editor-v2/custom-templates/radio-or-checkbox-edit.njk, designer/server/src/views/forms/editor-v2/custom-templates/radios-or-checkboxes.njk, designer/server/src/views/forms/editor-v2/partials/question-details-base.njk, model/src/form/form-editor/index.ts
Reworked anchor
Validation to ensure uniqueness on list item entries
=> Two or more list items needed

designer/server/src/createServer.ts
I will revert this once I have the information I need.
=> Log headers for testing

designer/server/src/lib/error-boom-helper.js, designer/server/src/models/forms/editor-v2/advanced-settings-fields.js, designer/server/src/models/forms/editor-v2/base-settings-fields.js, designer/server/src/routes/forms/editor-v2/guidance.test.js, designer/server/src/routes/forms/editor-v2/question-details.test.js, designer/server/src/routes/forms/editor-v2/questions.test.js, model/src/components/file-types.ts, model/src/components/index.ts
Moved file type definitions into forms-model so forms-runner can share them
Corrected a series of error messages based on Laura's review of my temporary wording
=> 528772 error messages

model/src/form/form-definition/index.ts
https://dev.azure.com/defragovuk/DEFRA-CDP/_workitems/edit/480840
=> Add trim to all schema strings

designer/server/src/models/forms/editor-v2/advanced-settings-fields.js, designer/server/src/routes/forms/editor-v2/question-details-errors.test.js, designer/server/src/routes/forms/editor-v2/question-details.test.js
Fixed error message
Added unit tests
=> Added unit tests

designer/server/src/lib/error-boom-helper.js, designer/server/src/models/forms/editor-v2/advanced-settings-fields.js, designer/server/src/routes/forms/editor-v2/question-details-errors.test.js, model/src/form/form-editor/index.ts
Min file count changed to prevent zero - and changed error message
Max days in past/future - changed message and limits
=> Fixed file and date error messages

designer/server/src/models/forms/editor-v2/questions.js
https://dev.azure.com/defragovuk/DEFRA-CDP/_workitems/edit/548056
=> Use flashed formValues on page error

designer/server/src/routes/forms/editor-v2/question-details.js, designer/server/src/routes/forms/editor-v2/question-type.js, designer/server/src/routes/forms/editor-v2/question-type.test.js
https://dev.azure.com/defragovuk/DEFRA-CDP/_workitems/edit/545603
=> Only do the page heading check for new questions

designer/server/src/models/forms/editor-v2/pages.js
https://dev.azure.com/defragovuk/DEFRA-CDP/_workitems/edit/545682
=> Add page title to the form overview page

designer/server/src/lib/session-helper.js, designer/server/src/models/forms/editor-v2/question-delete.js, designer/server/src/routes/forms/editor-v2/list-item-delete.js, designer/server/src/routes/forms/editor-v2/list-item-delete.test.js, designer/server/src/routes/forms/editor-v2/question-details-helper.js, designer/server/src/routes/forms/editor-v2/question-details-helper.test.js, designer/server/src/routes/forms/editor-v2/question-details.js, designer/server/src/routes/forms/index.js, designer/server/src/views/forms/editor-v2/custom-templates/radios-or-checkboxes.njk
Takes the user to a deletion confirmation page when they select to delete a list item from a radio or checkobox question
=> Confirmation page for delete list item

designer/server/src/config.ts, designer/server/src/models/forms/editor-v2/check-answers-settings.js, designer/server/src/models/forms/editor-v2/common.js, designer/server/src/models/forms/editor-v2/guidance.js, designer/server/src/models/forms/editor-v2/migrate.js, designer/server/src/models/forms/editor-v2/page.js, designer/server/src/models/forms/editor-v2/pages-reorder.js, designer/server/src/models/forms/editor-v2/pages.js, designer/server/src/models/forms/editor-v2/question-delete.js, designer/server/src/models/forms/editor-v2/question-details.js, designer/server/src/models/forms/editor-v2/question-type.js, designer/server/src/models/forms/editor-v2/questions.js
https://dev.azure.com/defragovuk/DEFRA-CDP/_boards/board/t/DXT%20Engineering/Stories?System.IterationPath=%40currentIteration&workitem=549416
Update page titles (browser tab) to the following format:
`{PageHeading} - {FormTitle} - Forms designer`
=> Update page titles

designer/client/src/javascripts/pages-reorder.js, designer/client/src/javascripts/pages-reorder.test.js, designer/server/src/common/components/pages-reorder-panel/_pages-reorder-panel.scss, designer/server/src/common/components/pages-reorder-panel/template.njk, designer/server/src/routes/forms/editor-v2/pages-reorder.js, designer/server/src/routes/forms/editor-v2/pages-reorder.test.js, designer/server/src/views/forms/editor-v2/pages-reorder.njk, designer/webpack.config.js, package-lock.json, package.json
https://dev.azure.com/defragovuk/DEFRA-CDP/_workitems/edit/545120
This PR introduces pages reordering via Javascript. All accessibility flows/ requirements have also been met. See ticket for all flows.
=> Feature 545120: Pages reorder via JS

designer/client/src/javascripts/preview/list-sortable.js, designer/server/src/routes/forms/editor-v2/question-details-helper.js, designer/server/src/routes/forms/editor-v2/question-details-helper.test.js, model/src/form/form-editor/types.ts
Fixed reorder button handlers being registered twice
Fixed missing default value on new list item
=> Two bug fixes for reordering (481094)

designer/client/src/javascripts/preview.js, designer/client/src/javascripts/preview.test.js, designer/client/src/javascripts/preview/list.js, designer/client/src/javascripts/preview/list.test.js, designer/client/src/javascripts/setup-preview.js, designer/server/src/common/components/preview-panel/_preview-panel.scss, designer/server/src/models/forms/editor-v2/question-details/preview.js, designer/server/src/models/forms/editor-v2/question-details/preview.test.js, model/src/form/form-editor/__stubs__/preview.js, model/src/form/form-editor/preview/checkbox-sortable.js, model/src/form/form-editor/preview/checkbox-sortable.test.js, model/src/form/form-editor/preview/date-input.js, model/src/form/form-editor/preview/email-address.js, model/src/form/form-editor/preview/index.js, model/src/form/form-editor/preview/list-sortable.test.js, model/src/form/form-editor/preview/long-answer.js, model/src/form/form-editor/preview/month-year.js, model/src/form/form-editor/preview/phone-number.js, model/src/form/form-editor/preview/question.js, model/src/form/form-editor/preview/radio-sortable.js, model/src/form/form-editor/preview/radio.js, model/src/form/form-editor/preview/uk-address.js, model/src/form/form-editor/preview/yes-no.js
Client side and server side render of checkboxes.
Also stops the jumping (due to border on highlight) when you hover over list elements.
Resolves: https://dev.azure.com/defragovuk/DEFRA-CDP/_workitems/edit/551308
=> Feat/551308  checkboxes preview

designer/server/src/models/forms/editor-v2/question-details/preview.js, designer/server/src/models/forms/editor-v2/question-details/preview.test.js, model/src/form/form-editor/index.ts
Fixes bug server side not showing on autocomplete options preview panel:
https://dev.azure.com/defragovuk/DEFRA-CDP/_boards/board/t/DXT%20Engineering/Stories?System.IterationPath=%40currentIteration&workitem=551282
=> feat: 551282 - Fix server side render

designer/server/src/lib/editor.js, designer/server/src/lib/editor.test.js, model/README.md, model/scripts/generate-schemas.js, model/scripts/schema-modules/utils.test.js, model/src/form/form-definition/index.test.ts, model/src/form/form-definition/index.ts, model/src/form/form-manager/types.ts
[Feature/552484](https://dev.azure.com/defragovuk/DEFRA-CDP/_workitems/edit/552484)
=> Validate document with read, modify & save

designer/client/src/conditions/ConditionsEdit.tsx, designer/client/src/conditions/SelectConditions.tsx, designer/client/src/data/condition/findCondition.ts, designer/client/src/data/condition/fixupConditions.ts, designer/client/src/data/list/findListItemReferences.ts, designer/client/src/stylesheets/_editor2.scss, designer/client/src/stylesheets/application.scss, designer/server/src/__stubs__/form-definition.js, designer/server/src/common/components/editor-card/_editor-card.scss, designer/server/src/models/forms/editor-v2/conditions.js, designer/server/src/models/forms/editor-v2/migrate.js, designer/server/src/routes/forms/editor-v2/conditions.js, designer/server/src/routes/forms/editor-v2/conditions.test.js, designer/server/src/routes/forms/index.js, designer/server/src/views/forms/editor-v2/conditions.njk, model/src/conditions/condition-abstract.ts, model/src/conditions/condition-group.ts, model/src/conditions/condition-model.test.ts, model/src/conditions/condition-model.ts, model/src/conditions/helpers.ts, model/src/conditions/index.ts, model/src/conditions/migration.test.ts, model/src/conditions/migration.ts
=> Manage conditions page

model/src/form/form-definition/index.ts, model/src/form/form-definition/types.ts
Add schema version to the model
First step for: https://dev.azure.com/defragovuk/DEFRA-CDP/_workitems/edit/551141
=> feat: 551141 - Add schema v2 to model

designer/server/src/models/forms/editor-v2/questions.js, model/src/pages/helpers.test.ts, model/src/pages/helpers.ts, model/src/pages/index.ts
Fix for repeater option not available on repeater page
=> fix: 559206 - Allow repeater on repeater controller

designer/client/src/stylesheets/_editor2.scss, designer/package.json, designer/server/src/__stubs__/form-definition.js, designer/server/src/common/constants/session-names.js, designer/server/src/lib/editor.js, designer/server/src/lib/editor.test.js, designer/server/src/models/forms/editor-v2/common.js, designer/server/src/models/forms/editor-v2/common.test.js, designer/server/src/models/forms/editor-v2/conditions.js, designer/server/src/models/forms/editor-v2/page-conditions.js, designer/server/src/models/forms/editor-v2/page-conditions.test.js, designer/server/src/models/forms/editor-v2/questions.js, designer/server/src/models/forms/editor-v2/questions.test.js, designer/server/src/routes/forms/editor-v2/conditions.js, designer/server/src/routes/forms/editor-v2/conditions.test.js, designer/server/src/routes/forms/editor-v2/questions.test.js, designer/server/src/views/forms/editor-v2/page-conditions.njk, designer/server/src/views/forms/editor-v2/partials/page-navigation-tabs.njk, designer/server/src/views/forms/editor-v2/partials/question-details-preview-panel.njk, designer/server/src/views/forms/editor-v2/questions.njk, model/package.json, model/src/conditions/migration.test.ts, model/src/conditions/migration.ts, model/src/form/form-definition/index.test.ts, model/src/form/form-definition/index.ts, model/src/form/form-definition/types.ts, package-lock.json, package.json
https://dev.azure.com/defragovuk/DEFRA-CDP/_workitems/edit/556321
This PR introduces the ability to assign and remove a condition to/ from a page.
https://github.com/user-attachments/assets/55fbbe9a-0441-4d7a-9761-3913ab53e7cf
=> Feature 556321: Assign condition to page

designer/server/src/common/components/pages-reorder-panel/_pages-reorder-panel.scss, designer/server/src/models/forms/editor-v2/condition-check-changes.js, designer/server/src/models/forms/editor-v2/condition-check-changes.test.js, designer/server/src/models/forms/editor-v2/condition.js, designer/server/src/routes/forms/editor-v2/condition-check-changes.js, designer/server/src/routes/forms/editor-v2/condition-check-changes.test.js, designer/server/src/routes/forms/editor-v2/condition-helper.js, designer/server/src/routes/forms/editor-v2/condition-helper.test.js, designer/server/src/routes/forms/editor-v2/condition.js, designer/server/src/routes/forms/editor-v2/condition.test.js, designer/server/src/routes/forms/index.js, designer/server/src/views/forms/editor-v2/condition-check-changes.njk, designer/server/src/views/forms/editor-v2/condition.njk, model/src/form/form-editor/types.ts
Shows original and new condition
Shows what pages (if any) are impacted by the condition change
=> Added check-changes conditions page

designer/client/src/javascripts/preview/__mocks__/nunjucks-renderer.js, designer/client/src/javascripts/preview/__stubs__/question.js, designer/client/src/javascripts/preview/autocomplete-renderer.js, designer/client/src/javascripts/preview/nunjucks-page-renderer.js, designer/client/src/javascripts/preview/nunjucks-renderer.js, designer/client/src/javascripts/preview/nunjucks-renderer.test.js, designer/client/src/javascripts/preview/page-controller/setup-page-controller.js, designer/client/src/javascripts/preview/page-controller/setup-page-controller.test.js, designer/client/src/views/page-preview-component/template.njk, designer/server/src/common/components/page-preview/template.njk, designer/server/src/common/components/preview-panel-layout/_preview-panel-layout.scss, designer/server/src/models/forms/editor-v2/questions.js, designer/server/src/models/forms/editor-v2/questions.test.js, model/src/form/form-editor/macros/types.ts, model/src/form/form-editor/preview/autocomplete.js, model/src/form/form-editor/preview/controller/page-controller.test.js, model/src/form/form-editor/preview/helpers.js, model/src/form/form-editor/preview/helpers.test.js, model/src/form/form-editor/preview/list.js, model/src/form/form-editor/preview/select-sortable.js, model/src/form/form-editor/preview/select.js, model/src/form/form-editor/preview/types.ts
This fixes the final two problems of the in progress page preview tickets.
- Autocomplete not registering as autocomplete (js function not being called), but staying as a select component
- Preview url
Resolved the autocomplete by reorganising the Nunjucks renderers a bit and using composition on the NunjucksPageRenderer
Ticket: https://dev.azure.com/defragovuk/DEFRA-CDP/_workitems/edit/551824
=> feat: 566025 - Fix autocomplete not rendering

designer/client/src/stylesheets/_editor2.scss, designer/server/src/common/components/pages-panel-left/template.njk, designer/server/src/common/components/pages-panel-left/template.test.js
Fixed issue where first condition not displayed
=> Added more spacing after green tick

designer/server/src/views/forms/editor-v2/partials/guidance-left-panel.njk
Added skip link (to page preview) on guidance page
Ticket [DF-73](https://eaflood.atlassian.net/browse/DF-73)
[DF-73]: https://eaflood.atlassian.net/browse/DF-73?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Added skip link on guidance page

designer/server/src/lib/editor.js, designer/server/src/lib/editor.test.js
https://eaflood.atlassian.net/browse/DF-83
=> Fix case where repeater settings are lost

designer/client/src/javascripts/application.js, designer/client/src/stylesheets/_editor2.scss, designer/server/src/common/components/preview-panel-tabs/template.njk, designer/server/src/views/forms/editor-v2/partials/page-settings.njk, designer/server/src/views/forms/editor-v2/partials/questions-left-panel.njk, designer/server/src/views/forms/editor-v2/question-details.njk, designer/server/src/views/forms/editor-v2/questions.njk
https://eaflood.atlassian.net/browse/DF-72?atlOrigin=eyJpIjoiMWRiMmI3MzkxNDIxNDBlN2E3MDNhMTc1YzMyNThhZTIiLCJwIjoiaiJ9
This PR introduces skip links in the page overview and preview and error preview panel.
=> Feature DF-72: skip links in page overview and preview panel

designer/server/src/common/components/page-body/macro.njk, designer/server/src/common/templates/layouts/page.njk
Body is wrapped in <div> so default skip link (going to #main-content) now goes to body content area
=> Skip link goes to body content

designer/server/src/models/forms/editor-v2/page.js, designer/server/src/models/forms/editor-v2/page.test.js, designer/server/src/routes/forms/editor-v2/page.test.js, designer/server/src/views/forms/question-radios.njk
https://eaflood.atlassian.net/browse/DF-155
=> Organise titles and heading on the choose page type page

designer/server/src/common/components/editor-card/_editor-card.scss, designer/server/src/views/forms/editor-v2/custom-templates/radios-or-checkboxes.njk
https://eaflood.atlassian.net/browse/DF-317?atlOrigin=eyJpIjoiYjgwYzQxZmY5Njk1NGQ4NTllMTczYzAxYmFiYmNiOWEiLCJwIjoiaiJ9
This PR fixes the disjointed text when the hint text of a list item is long.
=> Bug DF-317: Fix wrapping of long hint text in list item

designer/server/src/models/forms/create.js
Add missing fieldset from organisation page
=> Add missing fieldset to org view model

model/src/form/form-audit/types.ts
Allow data with just formId and slug
=> feat: DF-309 - Add FormMessageDataBase to FormMessageActivitiesData

designer/server/src/lib/manage.js, designer/server/src/routes/manage/user.js, designer/server/src/routes/manage/user.test.js, model/src/manage/types.ts, package-lock.json
Uses correct banner messages for user management pages:
- add user is handled
- amend user is handled
- delete user is handled
NOTE - since emails are not yet being sent out, the extra wording to say 'an email has been sent' is omitted for now
=> Corrected banner messages

model/src/form/form-audit/index.ts
Bad schema change is messing up manager
=> Feat/df 366  auditing tasks

designer/server/src/lib/editor.js, designer/server/src/lib/editor.test.js
https://eaflood.atlassian.net/browse/DF-405
=> bug DF-405: preserve repeater settings when updating question properties

designer/client/src/javascripts/preview/__stubs__/page.js, designer/server/src/models/forms/editor-v2/questions.js, designer/server/src/routes/forms/editor-v2/questions.js, model/src/form/form-definition/index.ts, model/src/form/form-editor/index.ts
https://eaflood.atlassian.net/browse/DF-425
=> Update repeater max items to 200

designer/server/src/__stubs__/form-definition.js, designer/server/src/models/forms/editor-v2/pages.js, designer/server/src/models/forms/editor-v2/pages.test.js, designer/server/src/routes/forms/editor-v2/pages.test.js, designer/server/src/views/forms/editor-v2/partials/conditions-filter.njk
Re-arranged filter panel
Ticket [DF-286](https://eaflood.atlassian.net/browse/DF-286)
[DF-286]: https://eaflood.atlassian.net/browse/DF-286?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Condition filter - Accessibility changes
