DEFRA/forms-designer

designer/client/babel.config.cjs, designer/nodemon.json, designer/package.json, designer/webpack.config.cjs, model/.browserslistrc, model/package.json, package.json
All ES module imports should be fully specified like `..` → `../index.js`
As a workaround for `@xgovformbuilder/govuk-react-jsx` we use Babel with webpack `{ fullySpecified: false }`
https://github.com/DEFRA/forms-designer/blob/6d71d55d7b0ef052793d2a71304c9f84d7ca817a/designer/webpack.config.cjs#L50-L59
But unfortunately webpack hits an [unknown `..` import in `govuk/template/index.js`](https://github.com/XGovFormBuilder/govuk-react-jsx/blob/main/src/govuk/template/index.js#L11)
This PR removes the `main` export in `@defra/forms-designer` so `govuk/index.js` is matched instead
=> Prevent unspecified `..` import in `@xgovformbuilder/govuk-react-jsx` resolving server

designer/package.json, designer/server/src/createServer.ts, designer/server/src/lib/persistence/index.ts, designer/server/src/lib/persistence/persistenceService.ts, designer/server/src/plugins/routes/api.ts, designer/server/src/plugins/routes/newConfig.ts, designer/server/src/types.ts, package-lock.json
This PR fixes [`schmervice`](https://www.npmjs.com/package/schmervice) which is now [`@hapipal/schmervice`](https://www.npmjs.com/package/@hapipal/schmervice)
This was missed from commit bd457aa3bf49682b405c2b3671861d060a95e00c and restores the `[]` namespace
=> Switch to updated `@hapipal/schmervice` package

designer/server/src/createServer.ts, designer/server/src/login/controller.js
This PR ensures tests always use mock authentication
This wasn't the case (locally) when `OIDC_WELL_KNOWN_CONFIGURATION_URL` was set
=> Always use mock auth in tests

designer/server/src/routes/library.test.js
Fixes the failing `library` route test but mocking the form manager api call to list the forms
=> Mock form manager api call to list forms

designer/package.json, designer/webpack.config.cjs, package-lock.json
This PR lets webpack handle Sass `@warn` and `@debug` and reduces unnecessary log output
I've also switched from [`sass`](https://www.npmjs.com/package/sass) (JavaScript) to [`sass-embedded`](https://www.npmjs.com/package/sass-embedded) (Dart executable) for a minor speed bump
=> Improve webpack Sass output + logging

designer/server/src/common/components/heading/template.njk, designer/server/src/plugins/routes/app.test.ts, designer/server/src/routes/library.test.js, designer/server/src/views/help/accessibility-statement.njk, designer/server/src/views/help/cookies.njk, designer/server/src/views/help/feedback.njk, designer/server/src/views/library.njk
Updates our new static pages from https://github.com/DEFRA/forms-designer/pull/69 to use the built in page content macros
=> Use `appHeading()` and `appPageBody()` for page content

.github/workflows/pr-notifier.yml
This PR swaps all codes to Emoji characters because it looks like `:speech_bubble:` didn't work via the API
From the [**Formatting: Emoji** documentation](https://api.slack.com/reference/surfaces/formatting#emoji) Slack says:
>If you're publishing text with emoji, you don't need to worry about converting them, just include them as-is.
=> Fix missing Slack emoji

.github/workflows/pr-notifier.yml
This PR skips the `pull_request_review` event for individual comments and replies
It's a bit noisy adding Slack comments for all code review comments
=> Only allow “approved” Slack code review comments

model/package.json, package-lock.json
Allow `npm install` to share a compatible `joi` and `nanoid` as `@defra/forms-model` **peerDependencies**
Otherwise each package can depend on their own mismatched versions:
```console
Cannot mix different versions of joi schemas (0)
80 |       })
81 |       .optional(),
> 82 |     components: joi.array().items(componentSchema)
```
I've included `nanoid` because `nanoid@4` and above is "ESM only" and won't work with Jest
This should prevent Dependabot PR checks from intentionally completing an `npm install` with an incompatible version
=> Move `joi` and `nanoid` to peer dependencies

model/src/form/form-metadata/index.ts
Fixes the 'Built-in TLD list disabled' error.
Unfortunately there's no quick domain filter, else I'd have gone a step further.
=> Add UK allow-list for email TLDs

designer/nodemon.json, designer/package.json, designer/server/src/config.ts, package-lock.json
This is only required for development, not in the live environment, therefore I've not modified `npm run start`.
=> Remove dotenv, replace with --env-var

designer/client/src/components/Flyout/Flyout.enzyme.test.tsx, designer/client/src/components/Flyout/Flyout.tsx, designer/client/src/components/RenderInPortal/RenderInPortal.test.tsx, package-lock.json, package.json
This PR fixes a few type issues in the `<Flyout>` component and enables `<RenderInPortal>` tests
Good to fix them ahead of any work on the form editor
=> Fix types for `<Flyout>` + enable `<RenderInPortal>` tests

.github/workflows/check-pull-request.yml
We shouldn't need to wait for `npm run build --workspace model` (and have it restored) for every lint task
See commit https://github.com/DEFRA/forms-designer/pull/116/commits/8c96cbb1e166c96e167ea680aa0e6aed1c88e467 for earlier changes made to support this
This frees up the "post build" step to spin up integration tests (maybe) etc
<br>
=> Split out GitHub Actions lint tasks to run before build

designer/server/src/routes/account/sign-out.js
We were adding `authedUser.loginHint` to `?logout_hint=` (typo?) but this isn't supported anyway
* https://github.com/keycloak/keycloak/issues/21399
We should look to add `?id_token_hint=` to enable sign out redirects in future
I've removed it for now to fix sign out locally
=> Remove unused `logout_hint` to fix Keycloak sign out

designer/package.json, designer/server/src/common/helpers/auth/azure-oidc.js, designer/server/src/common/helpers/auth/drop-user-session.js, designer/server/src/common/helpers/auth/get-user-session.js, designer/server/src/common/helpers/auth/pre/provide-authed-user.js, designer/server/src/common/helpers/auth/refresh-token.js, designer/server/src/common/helpers/auth/session-cookie.js, designer/server/src/common/helpers/auth/user-session.js, designer/server/src/common/nunjucks/context/index.js, designer/server/src/createServer.ts, designer/server/src/routes/account/auth.js, designer/server/src/routes/account/sign-out.js, designer/server/src/types.ts, designer/server/test/fixtures/auth.js, package-lock.json, package.json
This PR adds server methods for `session.get()`, `session.set()` and `session.drop()`
I've also typed `request.auth.user` as Hapi expects it to be with all utility methods now typed
Sessions are keyed using `claims.sub` so an expired token can seamlessly re-authenticate without session loss
```js
export function createUser(credentials) {
const claims = getUserClaims(credentials)
if (!claims) {
return
}
return /** @satisfies {UserCredentials} */ ({
id: claims.sub,
email: claims.email ?? '',
displayName: claims.name ?? '',
issuedAt: DateTime.fromSeconds(claims.iat).toUTC().toISO(),
expiresAt: DateTime.fromSeconds(claims.exp).toUTC().toISO()
})
}
```
**Note:** Session expiry checks are currently turned off
=> Update session management to use end-user ID + types

designer/server/src/common/components/error-summary/template.njk
This PR extends `appErrorSummary()` with support for custom errors not from Hapi
```njk
{% set errorHtml %}
We couldn’t sign you in. Please contact the system administrator for help,
<a href="mailto:steven.thomas@defra.gov.uk" class="govuk-link">steven.thomas@defra.gov.uk</a>
{% endset %}
{% if userFailedAuthorisation %}
{{ appErrorSummary({
errorList: [{
html: errorHtml | safe
}]
}) }}
{% endif %}
```
=> Extend wrapper `appErrorSummary()` for custom errors

designer/client/src/components/Visualisation/Visualisation.tsx, designer/client/src/designer.tsx, designer/client/src/index.tsx, designer/server/src/createServer.test.ts, designer/server/src/lib/forms.js, designer/server/src/routes/forms/editor.js, designer/server/src/routes/forms/editor.test.js, designer/server/src/routes/forms/library.test.js, designer/server/src/views/forms/editor.njk, designer/server/src/views/forms/library.njk
This PR overhauls how we pass data into the React editor UI
It uses the form ~`id`~ `slug` property in editor URLs and passes information to React via Nunjucks context
Thankfully this makes `slug` available for preview URLs too in a future PR
```js
return h.view('forms/editor', {
phase: config.phase,
previewUrl: config.previewUrl,
form: {
id: form.id,
slug: form.slug
}
})
```
```html
<div class="govuk-grid-column-full app-editor"
data-id="{{ form.id }}"
data-slug="{{ form.slug }}"
data-preview-url="{{ previewUrl }}">
</div>
```
=> Switch to form `slug` in editor URLs

.eslintrc.cjs, designer/server/src/lib/fetch.js, designer/server/src/routes/forms/create.js, designer/server/src/routes/forms/editor.js, model/src/form/form-metadata/index.test.js, model/src/form/form-metadata/index.ts
This PR adds validation to the "Form name" step to check if it's unique
I've also reviewed and updated validation messages with @Daniel-Da-Silveira
=> Add unique slug validation to “Form name” step

model/src/form/form-metadata/index.ts, model/src/form/form-metadata/types.ts
Just a small PR to make the `draft` state as optional (the draft state is now deleted on making the form live)
=> Remove required from  state in the FormMetadataSchema

designer/server/src/common/components/error-summary/macro.njk, designer/server/src/common/components/error-summary/template.njk, designer/server/src/common/helpers/build-error-details.js, designer/server/src/common/templates/layouts/page.njk, designer/server/src/models/forms/create.js, designer/server/src/routes/forms/create.js, designer/server/src/views/forms/question-input.njk, designer/server/src/views/forms/question-inputs.njk, designer/server/src/views/forms/question-radios.njk
This PR adds a new helper `buildErrorList()` so we can prepare Joi error objects for [**Error summary**](https://design-system.service.gov.uk/components/error-summary/)
This means we can configure the `pageTitle` "Error: " prefix in the Nunjucks layout
=> Move page `<title>` "Error: " prefix to layout

designer/server/src/common/helpers/build-error-details.js, designer/server/src/models/forms/create.js, designer/server/src/routes/forms/create.js, designer/server/src/views/forms/question-inputs.njk
This PR consolidates the create form schema and validates the entire payload before submission
It solves a problem when submitting the **Team details** step, where the form name may not be unique anymore
Errors found at the end of the create form journey will be redirected and displayed on the relevant step
This change enhances https://github.com/DEFRA/forms-designer/pull/147
=> Update "Create a new form" to redirect to previous steps with errors

designer/server/src/common/components/page-body/template.njk, designer/server/src/common/components/page-body/template.test.js, designer/server/src/common/components/service-header/template.njk, designer/server/src/common/helpers/auth/get-user-session.js, designer/server/src/common/helpers/auth/user-session.js, designer/server/src/config.ts, designer/server/src/createServer.test.ts, designer/server/src/models/forms/create.js, designer/server/src/models/forms/editor.js, designer/server/src/routes/forms/editor.js, designer/server/src/routes/forms/editor.test.js, designer/server/src/types.ts, designer/server/src/views/forms/editor.njk, designer/server/src/views/forms/question-input.njk, designer/server/src/views/forms/question-inputs.njk, designer/server/src/views/forms/question-radios.njk
Accidentally closed and re-opened from #162
---
This PR formats the user display name as `${firstName} ${lastName}`
* Phase banner turned off by default unless `PHASE=beta` is set etc
* Header account link defaults to “Sign in” (when signed out)
* Adds page title and back link to form editor
=> Update display name in header + other tweaks (re-opened)

designer/server/src/common/templates/layouts/page.njk
The phase banner (and Feedback link) was turned off in https://github.com/DEFRA/forms-designer/pull/163
This PR brings the Feedback link back but in the footer
=> Add “Feedback” link to footer

designer/server/src/common/components/service-header/_service-header.scss, designer/server/src/common/components/service-header/template.njk, designer/server/src/common/templates/partials/navigation.njk
This PR adds the green Defra header used on the prototype
We now use a `productName` and the `serviceName` is turned off by default
<br>
=> Add Defra service header

designer/server/src/common/nunjucks/context/build-navigation.js, designer/server/src/common/templates/partials/navigation.njk, designer/server/src/models/forms/library.js
This PR updates the `navigation` context for form overview and editor pages
I've also updated the `buildEntry()` helper to work without a Hapi request object
<br>
=> Add navigation entries for form overview and editor pages

designer/client/src/stylesheets/components/_all.scss, designer/client/src/stylesheets/components/_button.scss, designer/server/src/common/components/form-card/_form-card.scss, designer/server/src/common/components/form-card/macro.njk, designer/server/src/common/components/form-card/template.njk, designer/server/src/common/components/heading/template.njk, designer/server/src/common/components/heading/template.test.js, designer/server/src/models/forms/library.js, designer/server/src/views/account/signed-out.njk, designer/server/src/views/forms/editor.njk, designer/server/src/views/forms/library.njk, designer/server/src/views/forms/overview.njk, designer/server/src/views/forms/question-inputs.njk
This PR uses the grid layout changes in https://github.com/DEFRA/forms-designer/pull/169 to set up the "Form management" side bar
There's also some spacing changes around "Organisation details" and the preview link opens in a new tab
<br>
=> Set up "Form management" side bar + overview tweaks etc

designer/server/src/models/account/auth.js, designer/server/src/models/forms/create.js, designer/server/src/models/forms/library.js, designer/server/src/views/accessibility-statement.njk, designer/server/src/views/account/signed-out.njk, designer/server/src/views/cookies.njk, designer/server/src/views/feedback.njk, designer/server/src/views/forms/editor.njk, designer/server/src/views/forms/library.njk, designer/server/src/views/forms/overview.njk, designer/server/src/views/forms/question-inputs.njk
Using changes from https://github.com/DEFRA/forms-designer/pull/169 and https://github.com/DEFRA/forms-designer/pull/171 this PR add the following:
1. Changes the "Organisation details" heading to an `<h2>`
2. Sets up the correct "two-thirds" grid columns widths where necessary
3. Adds page heading params to routes with models
=> Set up "two-thirds" grid columns for headings etc

designer/server/src/common/helpers/auth/azure-oidc.js, designer/server/src/routes/forms/library.js, designer/server/src/routes/home.js, designer/server/test/fixtures/auth.js
This PR ensures `request.auth.isAuthorized` is flagged for signed in users
It also splits out our auth fixture into typed properties
=> Add user entity checks to routes

designer/server/src/common/components/page-body/macro.njk, designer/server/src/views/feedback.njk, designer/server/src/views/forms/question-input.njk, designer/server/src/views/forms/question-inputs.njk, designer/server/src/views/forms/question-radios.njk
This PR ensures the HTML `<form>` element wraps the page titles and error summary
It also fixes an issue where the error summary is displayed after the page title in **question-inputs.njk**
Error summary displays _after_ the page title
Error summary displays _before_ the page title
=> Update `appPageBody()` to support `params.errorList`

designer/server/src/views/forms/overview.njk
This PR adds a new summary list row to include the team email
=> Add “Shared team email address” to form overview

designer/client/src/components/ComponentCreate/ComponentCreate.scss, designer/client/src/components/Flyout/Flyout.scss, designer/client/src/components/Visualisation/visualisation.scss, designer/client/src/javascripts/application.js, designer/client/src/stylesheets/application.scss, designer/client/src/stylesheets/editor-colours.scss, designer/client/src/stylesheets/editor.scss, designer/package.json, designer/server/src/common/components/service-header/_service-header.scss, designer/server/src/common/components/service-header/template.njk, designer/server/src/common/nunjucks/environment.js, designer/webpack.config.js, package-lock.json
This PR upgrades to GOV.UK Frontend v5.4.0 (new tag style)
But I've configured webpack to allow GOV.UK Frontend v4.x assets used by the React components
=> Upgrade to GOV.UK Frontend v5.4.0

designer/server/src/models/forms/create.js, designer/server/src/routes/forms/create.js
This PR clarifies that the **Shared team email address** must be a valid UK email address
It also includes the following:
* Adds hint text to explain what the email address is used for
* Moves the "correct format" example from the error message to the hint text
This was discussed and agreed on Slack
=> Update hint and error message for shared team email

designer/server/src/common/helpers/auth/get-user-session.js, designer/server/test/fixtures/auth.js
Makes us consistent with the new setup on forms-manager
=> use the access token to check groups. 

babel.config.cjs, designer/babel.config.cjs, designer/client/babel.config.cjs, designer/package.json, designer/server/src/common/templates/layouts/page.njk, designer/webpack.config.js, model/babel.config.cjs, model/package.json
This PR enables webpack production settings to remove unused code
These file sizes are still not great but together with https://github.com/DEFRA/forms-designer/pull/190 we've made a considerable dent to load times in browsers
We now only use 5x components from `@xgovformbuilder/govuk-react-jsx`
```js
import {
Hint,
Input,
Label,
Select,
Textarea
} from '@xgovformbuilder/govuk-react-jsx'
```
---
909KB `editor.[hash].min.js`
38KB `application.[hash].min.js`
459KB `shared.[hash].min.js`
183KB `editor.[hash].min.js`
2KB `application.[hash].min.js`
=> Reduce editor JavaScript by 300KB

designer/client/src/ComponentEdit.js, designer/client/src/ComponentTypeEdit.tsx, designer/client/src/component.js, designer/client/src/components/ComponentCreate/ComponentCreateList.enzyme.test.tsx, designer/client/src/components/ComponentCreate/__snapshots__/ComponentCreateList.test.tsx.snap, designer/client/src/data/types.ts, designer/client/src/i18n/translations/en.translation.json, model/src/components/component-types.ts, model/src/components/enums.ts, model/src/components/types.ts
This PR removes the "Flash card" component from the editor now we've merged:
* https://github.com/DEFRA/forms-runner/pull/128
=> Remove HMPO components (i.e. Flash card) from editor

designer/client/src/components/ComponentCreate/ComponentCreate.test.tsx, designer/client/src/components/ComponentCreate/ComponentCreateList.enzyme.test.tsx, designer/client/src/link-create.test.tsx, designer/client/src/outputs/output-edit.test.tsx
Improves all our assertions on Jest mock calls where tests currently crash if mocks are _not_ called
=> Fix ESLint warnings for Jest mock calls

designer/server/src/common/constants/session-names.js, designer/server/src/common/helpers/auth/azure-oidc.js, designer/server/src/common/helpers/auth/get-user-session.js, designer/server/src/common/helpers/auth/refresh-token.js, designer/server/src/common/helpers/auth/session-cookie.js, designer/server/src/common/helpers/auth/user-session.js, designer/server/src/routes/account/auth.js, designer/server/src/types.ts
This PR ensures the previous URL path is restored after your session expires
We'll only be handling the URL path so I've renamed the yar key from `referrer` (full URL) → `redirectTo`
=> Restore previous URL path after auth callback

designer/server/src/routes/forms/library.test.js
Adds some missing author properties to test fixtures since https://github.com/DEFRA/forms-designer/pull/148 merged
=> Add missing `draft` author properties in tests

designer/client/src/reducers/component/componentReducer.test.tsx, designer/server/src/common/nunjucks/filters/format-date.test.js, jest.config.js
Couple of test fixes and strangely some React component assertions for imports that never existed
=> Remove component assertions for missing imports

designer/package.json, designer/webpack.config.js, model/babel.config.cjs, model/package.json
Just some old code tidy up since we no longer compile to CommonJS
Since we're removing lots of designer client code I've also reverted https://github.com/DEFRA/forms-designer/commit/6541796f62b6310343cde81ed8c6055c6979ace6
This re-includes `@defra/forms-model` so important Babel polyfills or transforms aren't missed
=> Remove unnecessary `BABEL_ENV` switching

designer/client/src/ComponentEdit.tsx, designer/client/src/FieldEdit.tsx, designer/client/src/MultilineTextFieldEdit.tsx, designer/client/src/components/Autocomplete/Autocomplete.tsx, designer/client/src/components/ComponentCreate/ComponentCreate.tsx, designer/client/src/components/ComponentListSelect/ComponentListSelect.tsx, designer/client/src/components/CssClasses/CssClasses.tsx, designer/client/src/components/CustomValidationMessage/CustomValidationMessage.tsx, designer/client/src/components/FieldEditors/DateFieldEdit.tsx, designer/client/src/components/FieldEditors/DetailsEdit.tsx, designer/client/src/components/FieldEditors/ListContentEdit.tsx, designer/client/src/components/FieldEditors/NumberFieldEdit.tsx, designer/client/src/components/FieldEditors/ParaEdit.tsx, designer/client/src/components/FieldEditors/TextFieldEdit.tsx, designer/client/src/reducers/component/componentReducer.fields.ts, designer/client/src/reducers/component/componentReducer.meta.ts, designer/client/src/reducers/component/componentReducer.options.ts, designer/client/src/reducers/component/componentReducer.schema.ts, designer/client/src/reducers/component/componentReducer.test.tsx, designer/client/src/reducers/component/componentReducer.tsx, designer/client/src/reducers/component/types.ts, designer/client/src/reducers/listReducer.tsx
This PR fixes a bug where `hasValidated` was set for all component actions
I've switched to the original names as non-option `EDIT_*` and `SET_*` events would be great for auditing
```patch
import {
-   Actions
+   Fields,
+   Meta,
+   Options,
+   Schema
} from '~/src/reducers/component/types.js'
```
=> Fix bug affecting `hasValidated` state

designer/client/src/Designer.tsx, designer/client/src/components/Menu/Menu.test.tsx, designer/client/src/components/Menu/SubMenu.tsx, designer/client/src/components/Page/Page.test.tsx, designer/client/src/components/Page/Page.tsx, designer/client/src/components/Visualisation/Visualisation.test.tsx, designer/client/src/components/Visualisation/Visualisation.tsx, designer/client/src/index.tsx, designer/package.json, designer/server/src/common/nunjucks/filters/format-json.js, designer/server/src/common/nunjucks/filters/index.js, designer/server/src/models/forms/library.js, designer/server/src/routes/forms/library.js, designer/server/src/routes/forms/library.test.js, designer/server/src/views/forms/editor.njk, package-lock.json, package.json
This PR ensures the editor page shows a 404 error when the form definition is missing
The editor loads the JSON from `<script type="application/json">` to avoid hitting **forms-manager** twice
```js
<Designer
metadata={metadata}
definition={definition}
previewUrl={previewUrl}
/>
```
Previously the editor would get stuck whilst loading via the browser API
=> Show editor 404 when definition is missing

designer/client/src/conditions/InlineConditionsDefinitionValue.tsx, model/src/components/component-types.ts, model/src/components/helpers.ts, model/src/components/index.ts, model/src/components/types.ts, model/src/conditions/condition-field.ts, model/src/conditions/condition-operators.ts, model/src/conditions/types.ts
This fixes a bug where conditional date fields attempted to render for text inputs etc
I've added a new helper `isConditionalType()` since it's safer to assume other bugs exist (and can be avoided)
=> Render null for unsupported conditional fields

designer/client/src/MultilineTextFieldEdit.tsx, designer/client/src/components/FieldEditors/DateFieldEdit.tsx, designer/client/src/components/FieldEditors/NumberFieldEdit.tsx, designer/client/src/components/FieldEditors/SelectFieldEdit.tsx, designer/client/src/components/FieldEditors/TextFieldEdit.tsx, designer/client/src/i18n/translations/en.translation.json
This PR fixes the "rows" option when editing a Textarea component (multi-line text)
The rows option was a single `<input>` without a label, resting on top of **Autocomplete**
These settings were missing a wrapper so fixed them at the same time
=> Fix textarea "rows" option

.eslintrc.cjs, designer/client/src/Component.tsx, designer/client/src/DeclarationEdit.tsx, designer/client/src/LinkCreate.tsx, designer/client/src/LinkEdit.tsx, designer/client/src/PageCreate.tsx, designer/client/src/PageEdit.tsx, designer/client/src/components/Visualisation/Lines.tsx, designer/client/src/components/Visualisation/Visualisation.tsx, designer/client/src/conditions/InlineConditions.tsx, designer/client/src/conditions/SelectConditions.tsx, designer/client/src/section/SectionEdit.tsx, designer/client/src/section/SectionsEdit.tsx
We use `this.context` data for form definitions but sometimes pass them via `this.props`
This can cause the two to get out of sync
=> Fix mismatch of `data` shared through props or context

docker-compose.yaml
This PR prevents our Docker services restarting automatically (e.g. after a reboot)
When following the README you'll currently see `docker compose up` reconnects rather than starts
```patch
-   restart: always
+   restart: unless-stopped
```
>Similar to `always`, except that when the container is stopped (manually or otherwise), it isn't restarted even after Docker daemon restarts.
=> Prevent docker services from restarting when stopped

designer/client/jest.environment.js, designer/client/src/Component.tsx, designer/client/src/Designer.tsx, designer/client/src/LinkCreate.test.tsx, designer/client/src/LinkEdit.test.tsx, designer/client/src/PageCreate.test.tsx, designer/client/src/PageCreate.tsx, designer/client/src/components/Menu/Menu.test.tsx, designer/client/src/components/Menu/Menu.tsx, designer/client/src/components/Page/Page.test.tsx, designer/client/src/components/Page/Page.tsx, designer/client/src/components/RenderInPortal/RenderInPortal.test.tsx, designer/client/src/components/RenderInPortal/RenderInPortal.tsx, designer/client/src/components/Visualisation/Lines.tsx, designer/client/src/components/Visualisation/Visualisation.test.tsx, designer/client/src/components/Visualisation/getLayout.ts, designer/client/src/components/Visualisation/visualisation.scss, designer/client/src/conditions/ConditionsEdit.test.tsx, designer/client/src/conditions/ConditionsEdit.tsx, designer/client/src/conditions/SelectConditions.test.tsx, designer/client/src/i18n/translations/cy.translation.json, designer/client/src/i18n/translations/en.translation.json, designer/client/src/stylesheets/editor.scss, designer/client/test/helpers/renderers-lists.tsx, designer/server/src/views/forms/editor.njk
This PR adds horizontal scrolling to the editor as part of [story #341960](https://dev.azure.com/defragovuk/DEFRA-CDP/_workitems/edit/341960)
Also included:
1. Open all "flyout" modals in `<RenderInPortal>` to avoid scroll overflow
2. Fix component icon colour and weight where link styles conflicted
3. Styled the condition captions that appear on the lines between pages
4. Renamed "Create component" → "Add component" buttons to match modals
https://github.com/DEFRA/forms-designer/assets/415517/6087cf82-3777-4e74-99a2-e92c50ab50a4
=> Add horizontal scrolling to editor

designer/client/src/PageEdit.tsx, designer/client/src/data/component/updateComponent.ts, designer/client/src/data/page/deleteLink.ts, designer/client/src/data/page/updateLink.ts, designer/server/src/routes/forms/api.test.js, model/src/form/form-definition/index.ts
This PR updates the form definition schema to make journey start pages optional and fixes a regression in:
* https://github.com/DEFRA/forms-designer/pull/269
Forms cannot currently be saved when pages are orphaned after:
1. Removing a page
2. Removing a link
3. Updating a page link
4. Updating a page path
The same applies following a JSON form definition upload with:
* Missing or null `startPage`
* Empty `startPage` like `''`
* Invalid `startPage` like `/error-404`
* Incorrect `startPage` like `/step-two`
Whilst start pages are mandatory for live forms, it's common for orphaned pages during development
JavaScript errors are logged in the form editor when deleting links between pages
The error comes from **forms-manager** during schema validation:
```console
[server]     err: {
[server] …
```
=> Allow form definition with optional `startPage` and `phaseBanner`

designer/package.json, designer/server/src/common/helpers/auth/azure-oidc.js, designer/server/src/common/helpers/auth/refresh-token.js, designer/server/src/common/helpers/auth/session-cookie.js, designer/server/src/lib/fetch.js, designer/server/src/lib/oidc.js, designer/server/src/routes/account/sign-out.js, package-lock.json
- Adds support for proxied calls through https_proxy and http_proxy
- Reduces duplicaton, makes calling the external OIDC provider consistent with the forms-manager API's `forms.js` helpers.
=> Move API calls to Wreck

designer/package.json, designer/server/src/common/constants/session-names.js, designer/server/src/common/helpers/build-error-details.js, designer/server/src/lib/fetch.js, designer/server/src/models/forms/form-lifecycle.js, designer/server/src/routes/forms/form-lifecycle.js, designer/server/src/types.ts, designer/server/src/views/forms/make-draft-live.njk, package-lock.json
Ticket: https://dev.azure.com/defragovuk/DEFRA-CDP/_workitems/edit/401610
When a user tries to promote a draft form but it fails, display the error message to the user
Current, forms-manager reports back three errors for bad request:
- This form is already live. Create a new draft to change the form.
- The questions in this form are not all connected. Connect all pages within the form.
- The draft form does not contain an output email address. Add an output email address for forms to be sent to.
Dan will be reviewing wording for the latter, but won't be a blocker for this PR.
To be deployed after https://github.com/DEFRA/forms-manager/pull/200.
=> Surface error messages to the user when making an invalid form live

designer/client/src/Component.tsx, designer/client/src/ComponentTypeEdit.test.tsx, designer/client/src/FieldEdit.test.tsx, designer/client/src/FieldEdit.tsx, designer/client/src/components/Autocomplete/Autocomplete.test.tsx, designer/client/src/components/ComponentListSelect/ComponentListSelect.test.tsx, designer/client/src/components/CssClasses/CssClasses.test.tsx, designer/client/src/components/CustomValidationMessage/CustomValidationMessage.test.tsx, designer/client/src/components/FieldEditors/DateFieldEdit.test.tsx, designer/client/src/components/FieldEditors/NumberFieldEdit.test.tsx, designer/client/src/components/FieldEditors/TextFieldEdit.test.tsx, designer/client/src/components/FieldEditors/TextFieldEdit.tsx, designer/client/src/components/Page/Page.tsx, designer/client/src/reducers/component/componentReducer.test.tsx, designer/client/src/reducers/component/componentReducer.tsx, designer/client/src/section/SectionEdit.test.tsx, model/src/components/types.ts
This PR disables the option `hideTitle` for components with a mandatory `<label>` or `<legend>`
Page titles will continue to automatically replace form legends or labels on single-question pages
For more information see the related **forms-runner** PR:
* https://github.com/DEFRA/forms-runner/pull/209
I've also fixed a few mismatched component options so they match their **forms-runner** usage, for example:
1. Missing option `required` on number component
2. Missing option `condition` on conditional components
3. Incorrect mandatory option `hint` on number and date components
I've also enabled `customValidationMessage` for more components:
* Email address component
* Month and year component
* Multiline text component
* Number component
* Text input component
These were supported by …
=> Only allow option `hideTitle` to remove UK address title etc

designer/client/src/components/Visualisation/Lines.tsx
Super quick fix to avoid confusion, see [story #409869](https://dev.azure.com/defragovuk/DEFRA-CDP/_workitems/edit/409869)
No condition in Chrome, Edge or Firefox (Safari works)
Condition tag is rendered correctly
=> Preserve 100px × 30px safe space for condition tag

designer/client/jest.environment.js, designer/client/src/ComponentTypeEdit.tsx, designer/client/src/FieldEdit.tsx, designer/client/src/MultilineTextFieldEdit.enzyme.test.tsx, designer/client/src/MultilineTextFieldEdit.tsx, designer/client/src/components/Autocomplete/Autocomplete.tsx, designer/client/src/components/CssClasses/CssClasses.tsx, designer/client/src/components/CustomValidationMessage/CustomValidationMessage.tsx, designer/client/src/components/FieldEditors/DateFieldEdit.tsx, designer/client/src/components/FieldEditors/DetailsEdit.test.tsx, designer/client/src/components/FieldEditors/DetailsEdit.tsx, designer/client/src/components/FieldEditors/ListContentEdit.tsx, designer/client/src/components/FieldEditors/NumberFieldEdit.tsx, designer/client/src/components/FieldEditors/ParaEdit.tsx, designer/client/src/components/FieldEditors/TextFieldEdit.enzyme.test.tsx, designer/client/src/components/FieldEditors/TextFieldEdit.tsx, designer/server/src/common/nunjucks/plugin.js, designer/server/src/lib/oidc.js, designer/server/src/models/forms/form-lifecycle.js, designer/server/src/routes/account/index.js, designer/server/src/routes/forms/index.js, designer/server/src/routes/index.js
This PR ensures "edit component" pages only render when `selectedComponent` exists in state
Some of our tests relied on partly-broken pages to be rendered with no known component
=> Skip render when selected component is undefined

designer/client/src/Designer.tsx, designer/client/src/Editor.tsx, designer/client/src/components/DataPrettyPrint/DataPrettyPrint.tsx, designer/client/src/components/Menu/Menu.test.tsx, designer/client/src/components/Menu/Menu.tsx, designer/client/src/components/Menu/SubMenu.tsx, designer/client/src/components/Menu/useMenuItem.tsx, designer/client/src/components/Tabs/Tabs.tsx, designer/client/src/context/DataContext.ts, designer/client/src/i18n/translations/en.translation.json, designer/client/src/index.tsx, designer/client/src/stylesheets/editor.scss, designer/client/test/helpers/renderers.tsx, tsconfig.base.json
Rather than remove "Summary" this renamed it to "Form overview" and drops it into the sub navigation
* The button "Summary" is now for the actual check answers summary
* The form summary tabs have moved into the sub navigation as "Form overview"
Since this was a useful feature, I've added the "Form metadata" tab and turned on syntax highlighting
=> Add form metadata to info tabs, rename to "Form overview"

.github/workflows/check-pull-request.yml, jest.config.js
Looks like some ESLint issues could be caused by `@defra/forms-model` not being built yet
This PR adjusts our ESLint checks to wait for the build to complete first
=> Run GitHub Actions lint tasks after build

designer/client/src/Component.tsx, designer/client/src/components/Page/Page.tsx, designer/client/src/i18n/translations/en.translation.json
Just realised we don't have screen reader announcements for:
1. Edit page
1. Add component
2. Preview icons for components
Let me know if you'd like a demo, they're now added
=> Add screen reader announcements for page visualisation

designer/server/src/common/templates/layouts/page.njk, designer/server/src/views/forms/editor.njk
This PR fixes calls to `getAssetPath()` to use the original asset resource filename
Unfortunately this was a side effect of `NODE_ENV=production` that was missed from the assets manifest JSON
**Context:** Since the [`webpack@5.93.0`](https://github.com/webpack/webpack/releases/tag/v5.93.0) update we've removed `css-loader` and `mini-css-extract-plugin` now that webpack `asset/resource` files added source map support out of the box
=> Fix stylesheet 404 error

model/src/form/form-definition/index.ts
These aren't supported by **forms-designer** and were removed in https://github.com/DEFRA/forms-runner/commit/0db32874cc440a45238645203cad601280956554
=> Remove unused localised string schema

model/src/components/helpers.ts, model/src/components/types.ts, model/src/conditions/condition-model.test.ts, model/src/conditions/condition-operators.ts
We have tests for select fields with conditions but they're not enabled in the UI
**Note:** We'd need to enable `number` lists to fully add "more than" and "less than" support etc
=> Fix missing `SelectField` component condition support

designer/client/src/conditions/ConditionsEdit.tsx
This PR fixes the conditions panel to render the condition "presentation string" instead of `()`
Nicely spotted by the type fixes in https://github.com/DEFRA/forms-designer/pull/351 where the previous UI was left out of date
The legacy `condition.expression` is undefined so is rendered as `()`
The correct `model.toPresentationString()` now rendered correctly
=> Fix condition presentation in “Add or edit condition”

designer/server/src/views/forms/library.njk
Since https://github.com/DEFRA/forms-designer/pull/340 we now have top-level form updated by/at values. This PR uses them on the library page, rather than the value from the draft/live.
This is being brought in under ticket #398639, [based on our Slack conversation](https://defra-digital-team.slack.com/archives/C071FRPN9TK/p1721138889548189).
=> #398639 Use the form's last updated in the library page

designer/client/src/conditions/AbsoluteDateValues.tsx, designer/client/src/conditions/RelativeTimeValues.tsx, designer/client/src/i18n/translations/en.translation.json
This PR fixes a regression where month/day/year condition values hit `Date.parse()` without padded zeroes
This was split out of the work to resolve:
1. [**Amended conditions are not being saved** #405841](https://dev.azure.com/defragovuk/DEFRA-CDP/_workitems/edit/405841)
2. [**Date conditions not working** #418871](https://dev.azure.com/defragovuk/DEFRA-CDP/_workitems/edit/418871)
Missing labels were also added in to fix the UI
=> Fix date condition validation (pad numbers before parsing)

designer/client/src/conditions/InlineConditionsDefinitionValue.test.tsx, designer/client/src/conditions/SelectValues.tsx, designer/client/src/conditions/TextValues.tsx
This PR fixes and re-enables the inline condition definition tests (skipped since 2021)
* Fix typo on condition list item `label` → `text`
* Fix inline conditions not being unset when blank
* Prefer input via label selectors in tests
* Add missing tests for absolute date conditions
=> Fix skipped inline condition definition tests

designer/client/src/conditions/InlineConditions.tsx, designer/client/src/i18n/translations/en.translation.json
This PR removes a warning message missed from https://github.com/DEFRA/forms-designer/pull/351/commits/26fffd7f8cc7dfbc0666aef667a36b9e905c418d in [#351](https://github.com/DEFRA/forms-designer/pull/351)
It was displayed when string conditions (removed) were edited in **forms-designer**
>You cannot edit this condition 'XYZ'. Please recreate it in the editor below to continue
=> Remove legacy condition string warning message

model/src/conditions/condition-model.test.ts, model/src/conditions/condition-operators.ts
This PR ensures story [#418871](https://dev.azure.com/defragovuk/DEFRA-CDP/_workitems/edit/418871) is ready for testing
It fixes one extra double-quote bug to prevent **forms-runner** from throwing an error, following on from:
* https://github.com/DEFRA/forms-designer/pull/366
The bug affected lines [234-237 of **FormModel.ts**](https://github.com/DEFRA/forms-runner/blob/6eaada2d316553aa8202c7100f38cd8ff53a45b2/src/server/plugins/engine/models/FormModel.ts#L234-L237) where condition objects are turned into expression strings
```console
exampleDate > ''2024-07-30''
```
```console
exampleDate > '2024-07-30'
```
=> Fix double-quoted absolute date condition expressions

designer/client/src/ComponentTypeEdit.test.tsx, designer/client/src/ComponentTypeEdit.tsx, designer/client/src/FieldEdit.tsx, designer/client/src/components/ComponentCreate/ComponentCreateList.enzyme.test.tsx, designer/client/src/components/ComponentCreate/ComponentCreateList.tsx, designer/client/src/components/ComponentCreate/__snapshots__/ComponentCreateList.test.tsx.snap, designer/client/src/components/FieldEditors/ConditionEdit.tsx, designer/client/src/components/FieldEditors/ParaEdit.tsx, designer/client/src/data/component/inputs.ts, model/src/components/helpers.test.ts, model/src/components/helpers.ts, model/src/components/index.ts, model/src/components/types.ts, model/src/conditions/condition-field.ts, model/src/conditions/condition-operators.ts
This PR resolves a couple of issues split out from https://github.com/DEFRA/forms-designer/pull/377
1. Conditions could not be selected when editing form components
2. Conditions could not be configured for autocomplete + telephone components
Fixes [bug #424825](https://dev.azure.com/defragovuk/DEFRA-CDP/_workitems/edit/424825)
All components now support conditions except for:
* Inset text component
* List component
* Month year component
* UK address component
I've also updated the types for `InputFieldsComponentsDef` and `SelectionComponentsDef` so we can type all known components with the `hint` property in forms runner by excluding content components:
```js
hint?: Exclude<ComponentDef, ContentComponentsDef>['hint']
```
Thanks to https://github.com/DEFRA/forms-designer/pull/378 we can …
=> Enable conditions UI for all supported components

designer/client/src/ComponentTypeEdit.test.tsx, designer/client/src/ComponentTypeEdit.tsx, designer/client/src/FieldEdit.test.tsx, designer/client/src/FieldEdit.tsx, designer/client/src/components/ComponentListSelect/ComponentListSelect.tsx, designer/client/src/components/FieldEditors/ListContentEdit.tsx, designer/client/src/i18n/translations/en.translation.json, model/src/components/types.ts
This PR adds a few extra **List** component fixes whilst testing the condition UI
1. Add option to hide list title
2. Remove unused "Name" field
3. Restore bullet formatting option that wasn't wired up
Fixes [bug #424830](https://dev.azure.com/defragovuk/DEFRA-CDP/_workitems/edit/424830)
Unlike other content components (**Details**, **HTML**, **Inset text**) we show unnecessary fields for **List**
We also have formatting options in **ListContentEdit.tsx** but it's not wired up (is now)
=> Fix “List component” missing list formatting options

designer/client/src/components/Visualisation/Lines.tsx
Minor fix to allow condition labels to expand beyond the line they're on
Previous change only worked in Safari, now Chrome and Firefox are working
Closes [bug #409869](https://dev.azure.com/defragovuk/DEFRA-CDP/_workitems/edit/409869)
=> Fix condition label overflow

designer/client/test/fixtures/assets-manifest.json, designer/server/src/common/helpers/auth/get-user-session.js, designer/server/src/common/nunjucks/context/index.js, designer/server/src/common/nunjucks/context/index.test.js, designer/server/src/common/templates/partials/navigation.test.js, designer/server/src/config.ts, designer/server/test/fixtures/auth.js, designer/server/test/fixtures/request.js
This PR adds `isAuthorized` to the Nunjucks context to show the navigation menu again
See related changes in PR [#385](https://github.com/DEFRA/forms-designer/pull/385/files#diff-150daf490ebb63b71484a1baef5a2dbe3b1b4f5bf5d5a2bc70e56594ec0dfd46R7)
Lots of test coverage added too
=> Fix missing service navigation menu

designer/client/src/LinkCreate.test.tsx, designer/client/src/LinkCreate.tsx, designer/client/src/LinkEdit.test.tsx, designer/client/src/LinkEdit.tsx, designer/client/src/PageCreate.test.tsx, designer/client/src/PageCreate.tsx, designer/client/src/PageEdit.tsx, designer/client/src/components/Menu/Menu.tsx, designer/client/src/components/Page/Page.tsx, designer/client/src/components/Visualisation/Lines.tsx, designer/client/src/data/section/findSection.ts, designer/client/src/helpers.js, designer/client/src/helpers.test.tsx, designer/client/src/section/SectionEdit.test.tsx, designer/client/src/section/SectionEdit.tsx, designer/client/src/section/SectionsEdit.tsx, model/src/utils/helpers.test.js, model/src/utils/helpers.ts
This PR is in preparation for [bug #399485](https://dev.azure.com/defragovuk/DEFRA-CDP/_workitems/edit/399485) with types added to page components
Various differences have been fixed, including page paths generated differently when editing the page title
Changes include:
1. Always use `slugify()` to set page paths (including via title)
2. Consistent "Create section" and "Edit section" between create/edit pages
4. Removes unused helpers `toUrl()` and `camelCase()`
I've also removed `randomId()` from duplicate page paths, preferring the validation to kick in instead:
=> Fix differences between page create/edit components

designer/client/src/LinkCreate.tsx, designer/client/src/PageEdit.tsx, designer/client/src/components/ComponentCreate/ComponentCreate.scss, designer/client/src/components/ComponentCreate/ComponentCreate.tsx, designer/client/src/components/ComponentCreate/ComponentCreateList.tsx, designer/client/src/components/ComponentCreate/__snapshots__/ComponentCreateList.test.tsx.snap, designer/client/src/components/ComponentListSelect/ComponentListSelect.tsx, designer/client/src/components/Flyout/Flyout.scss, designer/client/src/components/Flyout/Flyout.tsx, designer/client/src/components/Page/Page.tsx, designer/client/src/components/Visualisation/Visualisation.tsx, designer/client/src/conditions/ConditionsEdit.tsx, designer/client/src/conditions/InlineConditions.tsx, designer/client/src/conditions/InlineConditionsDefinition.tsx, designer/client/src/conditions/InlineConditionsEdit.tsx, designer/client/src/conditions/RelativeDateValues.tsx, designer/client/src/conditions/SelectConditions.tsx, designer/client/src/conditions/SelectValues.tsx, designer/client/src/list/ListEdit.tsx, designer/client/src/list/ListItemEdit.tsx, designer/client/src/list/ListSelect.tsx, designer/client/src/stylesheets/editor.scss, designer/server/src/common/components/breadcrumbs/template.njk
This PR removes unnecessary `<></>` wrapper fragments along with unused CSS classes and IDs
With tests now using [`ByRole` queries](https://testing-library.com/docs/queries/byrole/) via https://github.com/DEFRA/forms-designer/pull/402 many more are no longer needed
**Note:** Best viewed with ["Hide whitespace" `?w=1`](https://github.com/DEFRA/forms-designer/pull/403/files?diff=unified&w=1) as lots of lines show indentation only
=> Remove unnecessary wrappers, classes, IDs

designer/client/src/ComponentEdit.tsx, designer/client/src/FieldEdit.tsx, designer/client/src/LinkCreate.tsx, designer/client/src/components/ComponentCreate/ComponentCreate.tsx, designer/client/src/components/ComponentListSelect/ComponentListSelect.tsx, designer/client/src/components/FieldEditors/ContentEdit.tsx, designer/client/src/list/ListEdit.tsx, designer/client/src/list/ListItemEdit.tsx, designer/client/src/reducers/component/componentReducer.tsx, designer/client/src/reducers/listReducer.tsx, designer/client/test/helpers/renderers-lists.tsx, designer/client/test/helpers/renderers.tsx
Quick PR to initialise (and reset) `errors` state when necessary
It was possible to submit the "Create list" form with errors, switch to "Edit list", and they were persisted
=> Fix form validation not clearing between pages (e.g. add list)

designer/server/src/routes/forms/api.js
This PR resolves an issue where browser error logging gets stuck in a loop
1. Error is caught
2. Error is logged
3. Logger throws
4. Repeat
Probably caused by a recent Pino update, a new webpack optimisation, or when the **forms-designer** `/api` endpoint responds with an empty `err: {}` object when Joi validation fails 😬 
```console
TypeError: Cannot read properties of undefined (reading 'Symbol(pino.msgPrefix)')
at LOG (/path/to/forms-designer/node_modules/hapi-pino/node_modules/pino/lib/tools.js:59:22)
at handler (file:///path/to/forms-designer/designer/server/src/routes/forms/api.js:104:13)
```
=> Fix browser pino logger `undefined` issue

designer/client/src/Component.tsx, designer/client/src/ComponentEdit.tsx, designer/client/src/DeclarationEdit.tsx, designer/client/src/components/ComponentCreate/ComponentCreate.test.tsx, designer/client/src/components/ComponentCreate/ComponentCreate.tsx, designer/client/src/components/Menu/Menu.tsx, designer/client/src/components/Page/Page.tsx, designer/client/src/section/SectionsEdit.tsx
This PR is related to https://github.com/DEFRA/forms-designer/pull/412 and fixes an issue where components could be saved multiple times
It prevents multiple renders and now save only when validated and not already saving/deleting
The error in MongoDB due to this race condition is now resolved
=> Fix duplicate render + save for component create/edit

designer/client/src/LinkEdit.test.tsx, designer/client/src/LinkEdit.tsx, designer/client/src/PageCreate.tsx, designer/client/src/PageEdit.tsx, designer/client/src/components/FieldEditors/ConditionEdit.tsx, designer/client/src/components/Menu/Menu.tsx, designer/client/src/components/Page/Page.tsx, designer/client/src/components/Visualisation/Lines.tsx, designer/client/src/conditions/ConditionsEdit.test.tsx, designer/client/src/conditions/InlineConditionsDefinition.tsx, designer/client/src/conditions/SelectConditions.test.tsx, designer/client/src/conditions/SelectConditions.tsx, designer/client/src/conditions/SelectValues.tsx, designer/client/src/i18n/translations/cy.translation.json, designer/client/src/i18n/translations/en.translation.json, designer/client/src/list/ListItemEdit.test.tsx, designer/client/src/list/ListItemEdit.tsx
This PR adds some small UI tweaks for consistency
1. Prefer "Add a new" or "Edit" text for conditions/sections
2. Align page create/edit views by moving "Link from" to the bottom
3. Add default "Select an XXX" empty option to all select menus
=> Consistent UI tweaks

designer/client/src/Component.tsx, designer/client/src/components/Page/Page.tsx, designer/client/src/components/Visualisation/Visualisation.test.tsx, designer/client/src/components/Visualisation/getLayout.ts, designer/client/test/helpers/renderers-lists.tsx, designer/server/src/common/components/service-header/service-header.js, designer/server/src/routes/forms/edit.test.js, model/src/utils/helpers.ts
This PR fixes a JavaScript error when importing JSON with unknown component types
We attempted to render `<ComponentIcon>` when it was `undefined` and the editor crashes
I've also included some minor type fixes and removed unused model helpers
=> Fix error on unknown component types etc

designer/client/src/PageCreate.tsx, designer/client/src/PageEdit.tsx, designer/client/src/components/ComponentCreate/ComponentCreate.tsx, designer/client/src/components/ComponentCreate/ComponentCreateList.tsx, designer/client/src/components/ComponentCreate/__snapshots__/ComponentCreateList.test.tsx.snap, designer/client/src/components/Flyout/Flyout.scss, designer/client/src/components/Flyout/Flyout.tsx, designer/client/src/components/Menu/Menu.tsx, designer/client/src/conditions/InlineConditions.tsx, designer/client/src/conditions/SelectConditions.tsx, designer/client/src/context/FlyoutContext.ts, designer/client/src/stylesheets/editor.scss, designer/client/test/helpers/renderers.tsx
This PR fixes an issue affecting long flyout titles (e.g. when editing lists)
I've also adjusted the heading order for accessibility and removed the -50px offset from the first flyout
No safe space around close button
Safe space added around close button
=> Fix title overflow affecting `<Flyout>` component

designer/client/src/PageCreate.tsx, designer/client/src/PageEdit.tsx, designer/client/src/data/page/findPathsTo.test.ts, designer/client/src/data/page/findPathsTo.ts, designer/client/src/helpers.js, designer/client/src/i18n/translations/en.translation.json, model/src/form/form-definition/types.ts, model/src/pages/page-types.ts, sonar-project.properties
This PR adds form validation to **Page type** and replaces hard coded options with `PageTypes`
It makes up [story **#294192**](https://dev.azure.com/defragovuk/DEFRA-CDP/_workitems/edit/294192) as part of three PRs:
* https://github.com/DEFRA/forms-designer/pull/444 (this PR)
* https://github.com/DEFRA/forms-designer/pull/443
* https://github.com/DEFRA/forms-designer/pull/445
=> Add form validation to page type options

designer/client/src/FieldEdit.tsx, designer/client/src/PageCreate.tsx, designer/client/src/PageEdit.tsx, designer/client/src/components/ComponentCreate/ComponentCreateList.tsx, designer/client/src/components/ComponentCreate/__snapshots__/ComponentCreateList.test.tsx.snap, designer/client/src/data/component/fields.ts, designer/client/src/data/page/findPathsTo.ts, designer/client/src/helpers.js, designer/client/src/i18n/translations/en.translation.json, model/src/components/component-types.ts, model/src/components/helpers.ts, model/src/components/index.ts, model/src/form/form-definition/types.ts, model/src/pages/helpers.ts, model/src/pages/index.ts
This PR enables the file upload component
It makes up [story **#294192**](https://dev.azure.com/defragovuk/DEFRA-CDP/_workitems/edit/294192) as part of three PRs:
* https://github.com/DEFRA/forms-designer/pull/444
* https://github.com/DEFRA/forms-designer/pull/443 (this PR)
* https://github.com/DEFRA/forms-designer/pull/445
Jump to [PR #445](https://github.com/DEFRA/forms-designer/pull/445) to see the file upload component complete with settings
The **File upload** component can't be listed on the "Add component" page because it requires its own page type
This means we need to:
1. Prevent file upload component being added to other pages
2. Prevent file upload component being added more than once 
3. Filter "Add component" list to allow content components on file upload pages
4. Filter …
=> Enable file upload component

designer/client/src/PageCreate.tsx
When adding a new page we default the page type to "Question page"
This PR fixes a bug where the state wasn't updated until the page type `onChange` event fired
=> Fix page type not set by default

designer/client/src/Component.tsx, designer/client/src/components/Page/Page.test.tsx
This PR fixes a regression where up/down sorting arrows appeared on single component pages
Added tests to make sure it won't happen again
Closes [story #440769](https://dev.azure.com/defragovuk/DEFRA-CDP/_workitems/edit/440769)
=> Fix up/down buttons showing for single component

.eslintrc.cjs, designer/client/src/Component.tsx, designer/client/src/PageCreate.tsx, designer/client/src/PageEdit.tsx, designer/client/src/components/ComponentCreate/ComponentCreate.tsx, designer/client/src/components/ComponentCreate/ComponentCreateList.tsx, designer/client/src/components/ComponentListSelect/ComponentListSelect.tsx, designer/client/src/components/DataPrettyPrint/DataPrettyPrint.tsx, designer/client/src/components/Flyout/Flyout.test.tsx, designer/client/src/components/Flyout/Flyout.tsx, designer/client/src/components/Menu/Menu.test.tsx, designer/client/src/components/Menu/Menu.tsx, designer/client/src/components/Menu/SubMenu.tsx, designer/client/src/components/Page/Page.test.tsx, designer/client/src/components/Page/Page.tsx, designer/client/src/components/Visualisation/Lines.tsx, designer/client/src/components/Visualisation/visualisation.scss, designer/client/src/conditions/ConditionsEdit.tsx, designer/client/src/conditions/InlineConditions.tsx, designer/client/src/conditions/InlineConditionsEdit.tsx, designer/client/src/conditions/SelectConditions.tsx, designer/client/src/list/ListEdit.tsx, designer/client/src/list/ListItems.tsx, designer/client/src/list/ListSelect.tsx, designer/client/src/list/ListsEdit.tsx, designer/client/src/section/SectionsEdit.tsx, designer/client/src/stylesheets/editor.scss, package-lock.json, package.json
This PR resolves a Sonar warning that editor uses links `<a href="#">` as buttons
I've installed the ESLint JSX accessibility plugin fixed all that were flagged
=> Fix Sonar warning to use buttons (not links) for actions

designer/client/src/ComponentTypeEdit.test.tsx, designer/client/src/LinkEdit.test.tsx, designer/client/src/components/ComponentCreate/ComponentCreate.test.tsx, designer/client/src/components/ComponentCreate/ComponentCreateList.test.tsx, designer/client/src/components/ComponentListSelect/ComponentListSelect.test.tsx, designer/client/src/components/FieldEditors/ListFieldEdit.test.tsx, designer/client/src/components/Flyout/Flyout.test.tsx, designer/client/src/components/Menu/Menu.test.tsx, designer/client/src/components/Page/Page.test.tsx, designer/client/src/components/Visualisation/Visualisation.test.tsx, designer/client/src/conditions/AbsoluteDateValues.test.tsx, designer/client/src/conditions/ConditionsEdit.test.tsx, designer/client/src/conditions/InlineConditionsDefinitionValue.test.tsx, designer/client/src/list/ListItemEdit.test.tsx
Quick tech debt PR to remove unnecessary `act()` and `waitFor()` calls in tests
=> Remove unnecessary `act()` and `waitFor()` calls in tests 

model/src/form/form-metadata/index.ts
https://dev.azure.com/defragovuk/DEFRA-CDP/_workitems/edit/342247
Notification email schema re-used the contact email schema, but that is `required()`.
Added a separate schema for it.
=> Make notification email optional

designer/client/src/components/Visualisation/Lines.tsx, designer/client/src/components/Visualisation/Visualisation.tsx, designer/client/src/components/Visualisation/visualisation.scss, designer/client/src/stylesheets/editor.scss
Another minor visual fix
This PR adds `left: 30px` to CSS to prevent a horizontal jump when `<Visualisation>` renders
I've also removed `width` and `height` from the `<Line>` SVG since it's always 100% of the page wrapper
=> Prevent 30px jump on `<Visualisation>` render

designer/server/src/common/templates/layouts/page.njk, designer/server/src/views/forms/editor.njk, designer/webpack.config.js
To speed up the forms designer I've moved the shared JavaScript bundle to legacy editor pages only
```patch
- <script type="module" src="/javascripts/shared.[hash].min.js"></script>
<script type="module" src="/javascripts/application.[hash].min.js"></script>
```
There's now a separate React vendor bundle which is only loaded when opening the legacy editor
```patch
- <script type="module" src="/javascripts/shared.[hash].min.js"></script>
+ <script type="module" src="/javascripts/vendor/react.[hash].min.js"></script>
<script type="module" src="/javascripts/editor.[hash].min.js"></script>
```
Packages such as `react-dom`, `focus-trap-react`, `joi-browser` and `i18next` are loaded when unnecessary
=> Set up vendor bundle for React

designer/client/jest.environment.js, designer/client/src/ComponentEdit.tsx, designer/client/src/LinkEdit.tsx, designer/client/src/PageCreate.tsx, designer/client/src/PageEdit.tsx, designer/client/src/components/ComponentCreate/ComponentCreate.tsx, designer/client/src/components/Menu/Menu.tsx, designer/client/src/conditions/InlineConditions.tsx, designer/client/src/hooks/list/useListItem/types.ts, designer/client/src/hooks/list/useListItem/useListItem.tsx, designer/client/src/i18n/i18n.tsx, designer/client/src/index.tsx, designer/client/src/list/ListEdit.tsx, designer/client/src/list/ListItemEdit.tsx, designer/client/src/reducers/component/componentReducer.meta.ts, designer/client/src/reducers/component/componentReducer.test.tsx, designer/client/src/reducers/component/componentReducer.validations.ts, designer/client/src/section/SectionEdit.tsx, designer/client/src/validations.ts, designer/webpack.config.js
This PR follows on from https://github.com/DEFRA/forms-designer/pull/497
Whilst the legacy editor is still around, we can improve it's page load performance a lot
I've added lazy loading via `await import()` using the same approach as **forms-runner** in:
* https://github.com/DEFRA/forms-runner/pull/222
```console
editor (721 KiB)
javascripts/vendor/react.8c6b7e2.min.js
javascripts/editor.99c8b02.min.js
```
```console
editor (474 KiB)
javascripts/vendor/react.40cbdb4.min.js
javascripts/editor.dad8440.min.js
```
**Update:** Drops down to 466 KiB when https://github.com/DEFRA/forms-designer/pull/493 is included
The following optimisations have been included:
1. **Remove `en.translation.json` from bundle**
We already use `i18next` to download `/assets/translations/*.json`
2. **Lazy load …
=> Reduce initial editor JavaScript by 247 KiB

designer/client/src/data/section/updateSection.test.ts, designer/client/src/data/section/updateSection.ts
This PR fixes the `updateSection()` helper to ensure section edits are saved for [bug #449547](https://dev.azure.com/defragovuk/DEFRA-CDP/_workitems/edit/449547)
Checks for missing sections were accidentally copied in https://github.com/DEFRA/forms-designer/commit/1117787f0c4bc1e2b3160ba3b514b8b92bc562a9 from `addSection()` into `updateSection()`
=> Remove "missing section" check from `updateSection()` helper

designer/webpack.config.js
This PR temporarily turns off Terser `mangle.properties` added in:
* https://github.com/DEFRA/forms-designer/pull/499
Unfortunately we now use multiple webpack bundles that mangle each file differently. We're also importing packages with Babel transforms that hold the original property value in strings (https://github.com/terser/terser/issues/1265)
E.g. The following browser console error was caused by `react` being named differently in two JS bundles
```console
TypeError: i.G is not a function. (In 'i.G((function(e,t){var n,r,o=e.className,a=e["q"],s=e.Y,l=e.W,c=e.hint,u=e.label,d=e.id,h=F(e,M),f=a;if(c){var v="".concat(d,"-hint");f+=" ".concat(v),n=i.createElement(D,j({},c,{id:v}))}if(s){var m=d?"".concat(d,"-error"):"";f+=" ".concat(m),r=i.createElement(R,j({},s,{id:m}))}return …
```
=> Temporarily turn off Terser `mangle.properties`

designer/client/src/ComponentEdit.test.tsx, designer/client/src/ComponentEdit.tsx, designer/client/src/ComponentTypeEdit.test.tsx, designer/client/src/FieldEdit.test.tsx, designer/client/src/FieldEdit.tsx, designer/client/src/PageCreate.tsx, designer/client/src/PageEdit.tsx, designer/client/src/i18n/translations/en.translation.json, designer/client/src/reducers/component/componentReducer.fields.ts, designer/client/src/reducers/component/componentReducer.test.tsx, designer/client/src/reducers/component/componentReducer.tsx, designer/client/src/reducers/component/componentReducer.validations.ts, designer/client/src/reducers/component/types.ts, designer/client/src/section/SectionEdit.test.tsx, designer/client/src/section/SectionEdit.tsx, designer/client/src/section/SectionsEdit.tsx, designer/client/src/validations.ts
This PR removes editor support for the generated "name" field from components and sections
I've also removed all unnecessary state where `initialName` or `section` was held for comparison
=> Remove editor support for component/section name

designer/client/src/conditions/InlineConditions.tsx, designer/client/src/i18n/translations/en.translation.json, designer/client/src/list/ListEdit.tsx, designer/client/src/section/SectionEdit.tsx, model/src/form/form-definition/index.ts
This PR adds missing editor validation for:
1. Duplicate condition display name
2. Duplicate section title
3. Duplicate list title
The corresponding schema have also been updated
=> Add validation for duplicate condition, section and list titles

model/src/pages/helpers.ts, model/src/pages/index.ts
This PR makes some `@defra/forms-model` changes to test out https://github.com/DEFRA/forms-designer/pull/523
1. Consolidate helper `isLinkablePage()` into `hasNext()`
2. Make `page` param optional in `getPageDefaults()` and `hasSection()` for consistency
=> Consolidate helper `isLinkablePage()` into `hasNext()`

.github/workflows/publish-model.yml
Quick fix to add `environment: production` missed from https://github.com/DEFRA/forms-designer/pull/523
=> Add missing `environment: production` to npm publish job

.github/workflows/check-pull-request.yml, .github/workflows/publish-model.yml, .gitignore, designer/babel.config.cjs, designer/client/babel.config.cjs, jest.config.js, model/babel.config.cjs, package-lock.json, package.json, sonar-project.properties
This PR outputs [Sonar generic test execution report](https://docs.sonarsource.com/sonarqube/latest/analyzing-source-code/test-coverage/generic-test-data/#generic-test-execution) XML and adds lint task caching
It also switches to the [Jest `v8` coverage provider](https://jestjs.io/docs/configuration#coverageprovider-string) and adjusts Babel output to make minimal transforms
=> Add Sonar generic test execution report + coverage

.github/dependabot.yml, .github/workflows/check-pull-request.yml, designer/client/src/components/Flyout/Flyout.scss, designer/client/src/components/Visualisation/visualisation.scss, designer/client/src/stylesheets/editor.scss, designer/client/src/stylesheets/partials/_formatting.scss, designer/client/src/stylesheets/partials/_navigation.scss, designer/package.json, designer/server/src/common/components/service-header/_service-header.scss, package-lock.json, package.json, stylelint.config.js
This PR adds [**Stylelint**](https://stylelint.io) to GitHub Actions using the [GDS Stylelint Config](https://github.com/alphagov/stylelint-config-gds)
Recommended fixes are also included and checks can be run manually with:
```console
npm run lint:scss
```
=> Add Stylelint for Sass linting

.github/workflows/check-pull-request.yml, .gitignore, jest.config.js, package-lock.json, package.json, sonar-project.properties
This PR includes three changes:
1. Switching back to Babel + Istanbul code coverage to fix missing coverage for type imports
2. Cache the jest code coverage against `github.sha` to ensure timestamps change per commit
3. Remove the generic test execution `report.xml` added in [#534](https://github.com/DEFRA/forms-designer/pull/534) as SonarCloud isn't using it
Whilst debugging 1) the coverage was updating but perhaps Sonar looks at the parent directory timestamp?
Creating the coverage report from scratch (versus overwriting each time) seems to solve the problem
=> Fix Sonar code coverage not updating

designer/client/src/PageCreate.tsx, designer/client/src/PageEdit.tsx, model/src/pages/helpers.ts, model/src/pages/index.ts
This PR moves **PageEdit.tsx** and **PageCreate.tsx** `getPageDefaults()` into state
By doing this we can remove an unnecessary helper `isQuestionPage()` and use `hasFormComponents()` instead
=> Remove unnecessary helper `isQuestionPage()`

model/src/form/form-definition/index.ts
Short term workaround to unblock a prod release. Credit to @colinrotherham for the suggestion.
=> Allow empty guidance component name/title.

designer/client/src/components/Tabs/Tabs.tsx
This PR fixes [bug #466616](https://dev.azure.com/defragovuk/DEFRA-CDP/_workitems/edit/466616)
We were accidentally double-rendering the GOV.UK Frontend [**Tabs** component](https://design-system.service.gov.uk/components/tabs/)
This is now thrown by [`govuk-frontend@5.7.0`](https://github.com/alphagov/govuk-frontend/releases/tag/v5.7.0) since https://github.com/alphagov/govuk-frontend/pull/5272
=> Prevent GOV.UK Frontend “already initialised” Tabs error

designer/client/src/DeclarationEdit.test.tsx, designer/client/src/DeclarationEdit.tsx, model/src/form/form-definition/index.test.ts, model/src/form/form-definition/index.ts, model/src/form/form-definition/types.ts
This PR removes the unused "Skip summary" feature which won't be part of upcoming design changes
See related PR in **forms-runner**
* https://github.com/DEFRA/forms-runner/pull/516
=> Remove unused “Skip summary” feature

designer/package.json, package-lock.json
This partially reverts commit 6c033dc4d6a9ec7bfa55080b0d0c78d798def1e9 until https://github.com/webpack/webpack/pull/18937 is released for [issue #18932](https://github.com/webpack/webpack/issues/18932)
=> Temporarily roll back to `webpack@5.95.0`

.github/workflows/publish.yml
Adds manual "Run workflow" feature already added to:
* https://github.com/DEFRA/forms-manager/pull/340
* https://github.com/DEFRA/forms-runner/pull/455
This is so we can publish https://github.com/DEFRA/forms-designer/pull/584 without requiring source code changes
=> Add manual publish via `workflow_dispatch`

designer/client/src/stylesheets/application.scss, designer/client/src/stylesheets/components/_tag-env.scss, designer/server/src/common/components/service-header/_service-header.scss, designer/server/src/common/components/service-header/template.njk, designer/server/src/common/components/tag-env/_tag-env.scss, designer/server/src/common/components/tag-env/macro.njk, designer/server/src/common/components/tag-env/template.njk, designer/server/src/common/nunjucks/context/index.js, designer/server/src/common/nunjucks/context/index.test.js, designer/server/src/common/templates/layouts/page.njk, designer/server/src/common/templates/partials/navigation.njk, designer/server/src/config.ts
Adds an environment tag to the header
<br>
<br>
<br>
<br>
<br>
=> Add environment identification tag in the header (409424)

designer/server/src/models/forms/form-lifecycle.js, designer/server/src/models/forms/library.js, designer/server/src/models/forms/library.test.js
This PR removes the `Editor` button when a form is live. It also increases test coverage by adding a test suite for `library.js`.
=> Bug(401603): Remove editor button when form is live

model/src/conditions/condition-model.test.ts, model/src/conditions/condition-operators.ts, model/src/conditions/condition-value-abstract.ts, model/src/conditions/condition-values.ts
Condition values that contain any single quotes would cause the form definition to fail to load in `forms-runner`.
This is because the condition expression itself is [wrapped in single quotes](https://github.com/DEFRA/forms-designer/blob/e4230d468acd3187256cc806787ef4d2daf2db04/model/src/conditions/condition-operators.ts#L166). This causes an exception when the expression is subsequently [passed into](https://github.com/DEFRA/forms-runner/blob/main/src/server/plugins/engine/models/FormModel.ts#L154) `expr-eval` inside `forms-runner`.
This PR escapes any single quotes found in the condition values when building the expression.
=> Escape single quotes in condition values when building the expression

model/src/components/types.ts
This PR fixes a minor type issue when mixing form + content components
All base interfaces `FormFieldBase`, `ContentFieldBase` and `DateFieldBase` now have properties in common
Preventing the following error:
```console
Types of property 'pages' are incompatible.
Type '({ path: string; components: { type: ComponentType.YesNoField; name: string; title: string; options: { required: true; }; }[]; section: string; next: ({ path: string; condition?: undefined; } | { path: string; condition: string; })[]; title: string; controller?: undefined; } | ... 4 more ... | { ...; })[]' is not assignable to type 'Page[]'.
```
=> Fix compiler issue with mixed component types

designer/client/src/PageEdit.tsx, designer/client/src/components/Page/Page.tsx, designer/client/src/data/component/fields.ts, model/src/form/form-definition/types.ts, model/src/pages/controller-types.ts, model/src/pages/enums.ts, model/src/pages/helpers.test.ts, model/src/pages/helpers.ts, model/src/pages/index.ts
This PR includes some tidy ups and test coverage:
* Remove unused "Home page" controller type
* Remove unnecessary helper `hasSection()`
Plus adds test coverage for these helpers:
* `getPageDefaults()`
* `hasComponents()`
* `hasFormComponents()`
* `hasNext()`
* `hasRepeater()`
=> Remove unused home page type etc

designer/server/src/plugins/errorPage.ts, designer/server/src/views/400.njk, designer/server/src/views/403.njk, designer/server/src/views/404.njk, designer/server/src/views/500.njk, designer/server/src/views/account/sign-in.njk, designer/server/src/views/account/signed-out.njk, designer/server/src/views/forms/library.njk, designer/server/src/views/forms/question-input.njk, designer/server/src/views/forms/question-inputs.njk, designer/server/src/views/forms/question-radios.njk
Supports 368034 to present a friendly error rather than JSON if the user changes the URL parameters.
=> Add error page for HTTP 400

designer/server/src/common/components/sorting/_sorting.scss
Quick alignment fix for [story #479043](https://dev.azure.com/defragovuk/DEFRA-CDP/_workitems/edit/479043)
=> Minor alignment fix for sorting options

model/src/utils/markdown.ts
Fixes [bug #492045](https://dev.azure.com/defragovuk/DEFRA-CDP/_workitems/edit/492045) but see also:
* https://github.com/DEFRA/forms-runner/pull/652
=> Avoid global scope using `new Marked()` instance

designer/server/src/models/forms/notification-email.js
Fixes a quick typo "~Must~ Emails must end with…" in [`ad84175`](https://github.com/DEFRA/forms-designer/commit/ad84175eb52b2cb69e9622a649ec77ed4cd1b3c0#diff-241a457c1c99be4257ba168e631649ed2e54e451748b4cafa9e3d73e07357efeR27)
=> Fix typo “Must must end with”

designer/package.json, designer/server/src/common/helpers/logging/logger-options.js, designer/server/src/common/helpers/request-tracing.js, designer/server/src/config.ts, designer/server/src/createServer.ts, designer/server/src/lib/file.js, designer/server/src/lib/forms.js, designer/server/src/lib/utils.js, designer/server/src/lib/utils.test.js, designer/server/src/plugins/errorPage.ts, designer/server/src/typings/hapi-tracing/index.d.ts, jest.config.js, package-lock.json
- Passes the request trace ID downstream so errors can be traced across multiple serviecs
- Log unhandled errors before we return a response, so we can spot what's going wrong with Andrew's access
=> Add trace ID to headers and log unhandled errors

designer/client/src/PagesEdit.test.tsx, designer/client/src/PagesEdit.tsx, designer/client/src/components/Page/Page.tsx, designer/client/src/stylesheets/_helpers.scss, designer/client/src/stylesheets/application.scss, designer/client/src/stylesheets/components/_visualisation.scss
For V2 only:
Add visual indicators to the visualisation:
Add visual indicators to the Pages list:
=> Add repeat, terminal and conditional visual indicators to pages

designer/README.md, designer/client/src/javascripts/application.js, designer/server/src/common/components/pagination/template.njk, designer/server/src/common/components/pagination/template.test.js, designer/server/src/common/components/search/_search.scss, designer/server/src/common/components/search/template.njk, designer/server/src/common/components/search/template.test.js, designer/server/src/common/components/sorting/template.njk, designer/server/src/common/components/sorting/template.test.js, designer/server/src/lib/forms.js, designer/server/src/lib/forms.test.js, designer/server/src/models/forms/library.js, designer/server/src/models/forms/library.test.js, designer/server/src/routes/forms/library.js, designer/server/src/routes/forms/library.test.js, designer/server/src/views/forms/library.njk
https://dev.azure.com/defragovuk/DEFRA-CDP/_workitems/edit/479076
This PR introduces the required UI changes for advanced search, effectively consuming https://github.com/DEFRA/forms-manager/pull/409. It allows users to filter on author, organisation(s) and status(es), as well as form name.
=> Feature 479076:  Advanced Search

model/src/form/form-definition/index.test.ts, model/src/form/form-definition/index.ts
Joi.string().default has been changed to use a callback - as the other approach was setting it once.
=> feat: 512490 - Use correct contract for default values

model/src/form/form-definition/index.test.ts, model/src/form/form-definition/index.ts
This PR updates the component name validation logic to restrict names strictly to uppercase and lowercase letters (^[a-zA-Z]+$). It removes support for numbers, underscores, and special characters. Corresponding tests have been updated to reflect and verify this stricter validation rule, building upon the regex validation changes introduced in the previous PR.
=> Fix 518654: Restrict component names to letters only 

designer/server/src/lib/editor.js, designer/server/src/lib/editor.test.js, designer/server/src/routes/forms/editor-v2/pages.js, designer/server/src/routes/forms/editor-v2/pages.test.js
When a user calls the v2 homepage (/library/v2-form/editor-v2/pages) on a v1 draft form -  a call is sent through to migrate the form to v2.  The page is then opened with the updated definition.
=> Feat/481464  migrate on homepage

designer/server/src/common/components/pages-reorder-panel/template.njk, designer/server/src/models/forms/editor-v2/question-details.js, designer/server/src/views/forms/editor-v2/pages-reorder.njk
The main alert after the pages have been reordered will be done as a separate PR. This just covers the button focus screen reader voice output.
=> Added screen reader for reorder buttons

.github/workflows/publish-model.yml, model/.gitignore, model/.npmignore
Update publish workflow and ignore files for schema directory inclusion
- Modified the GitHub Actions workflow to include the 'model/schemas' directory in the build paths.
- Updated .gitignore to ensure the 'schemas/' directory is correctly ignored.
- Adjusted .npmignore to clarify the intention of including the 'schemas/' directory in the published package.
=> chore: update publish workflow to include schemas in cache an exclude scripts

designer/server/src/common/components/editor-card/template.njk, designer/server/src/common/helpers/build-error-details.js, designer/server/src/common/helpers/build-error-details.test.js, designer/server/src/models/forms/editor-v2/base-settings-fields.js, model/src/form/form-editor/index.test.ts, model/src/form/form-editor/index.ts
This PR solves the issue of errors on lists not showing in the error panel.  The error messages are now shown, for example:
Duplicate items also now throw a 400 error with error message:
=> Advanced error handling

designer/server/src/routes/forms/editor-v2/question-details-helper.js, designer/server/src/routes/forms/editor-v2/question-details-helper.test.js, model/src/form/form-definition/index.test.ts, model/src/form/form-definition/index.ts, model/src/form/form-definition/types.ts, model/src/form/form-editor/types.ts
`forms-plugin` is using a list hint: { id: string; text: string }, so hint: string is colliding with this.  Updated now to resolve.
=> test: 537088 - Update hint schema

designer/server/src/common/helpers/auth/session-cookie.js, designer/server/src/common/helpers/auth/user-session.js
Reuse existing flowId when refreshing token and removed multiple default auth strategies
https://dev.azure.com/defragovuk/DEFRA-CDP/_workitems/edit/528875
=> Reuse existing flowId when refreshing token and removed multiple default auth strategies

designer/server/jest.setup.cjs, designer/server/src/createServer.test.ts, designer/server/src/createServer.ts, designer/server/src/routes/account/sign-out.test.js
To support the new URL, redirect the users to it if they load the old URL.
=> Redirect the user to the new URL if they're using the old one

designer/server/src/models/forms/contact/email.js, designer/server/src/models/forms/contact/online.js, designer/server/src/models/forms/contact/phone.js, designer/server/src/routes/forms/contact/email.js, designer/server/src/routes/forms/contact/email.test.js, designer/server/src/routes/forms/contact/online.js, designer/server/src/routes/forms/contact/online.test.js, designer/server/src/routes/forms/contact/phone.js, designer/server/src/routes/forms/contact/phone.test.js, designer/server/src/routes/forms/edit.test.js, designer/server/src/routes/forms/privacy-notice.test.js, designer/server/src/routes/forms/submission-guidance.test.js, designer/server/src/views/forms/contact/email.njk, designer/server/src/views/forms/contact/online.njk, designer/server/src/views/forms/contact/phone.njk
https://dev.azure.com/defragovuk/DEFRA-CDP/_workitems/edit/538542
Adds a delete button to the contact forms when the contact can be deleted.
Contact info can be deleted when the form s not live, or if it is, when there's at least 1 other contact info present out of phone, online and email.
=> Allow users to delete contact information

designer/server/src/common/components/editor-card/_editor-card.scss, designer/server/src/common/constants/editor.js, designer/server/src/routes/forms/editor-v2/question-details-extra.test.js, designer/server/src/routes/forms/editor-v2/question-details-helper.js, designer/server/src/routes/forms/editor-v2/question-details-helper.test.js, designer/server/src/views/forms/editor-v2/custom-templates/radios-or-checkboxes.njk, model/src/form/form-editor/types.ts
Branched from main
Used the same 'autofocus' mechanism as for page re-ordering in order to get the screenreader to immediately read the button label
However, although it works, the screenreading didn't seem 100% reliable. Let's see how the testing goes.
=> Re-order items with screenreader

model/src/form/form-definition/index.ts
https://dev.azure.com/defragovuk/DEFRA-CDP/_workitems/edit/549452
This PR introduces a small change to the `listSchema` by introducing a new error message
=> feat: listSchema validation messages for unique identifiers

designer/client/src/javascripts/preview/__stubs__/list.js, designer/client/src/javascripts/preview/list-sortable.js, designer/client/src/javascripts/preview/list-sortable.test.js, designer/server/src/views/forms/editor-v2/custom-templates/radios-or-checkboxes.njk
Added screenreader announcements
Local test coverage shows 94.07% whereas SonarCloud is always reporting 84.2% no matter how many extra tests I add.
=> Added screenreader announcement for reorder list items

designer/webpack.config.js
This should fix dev being down.  The nunjucks templates that are referenced on server were missing from the build.
=> fix: Failing client side nunjucks build

designer/server/src/__stubs__/form-definition.js, designer/server/src/models/forms/editor-v2/pages.js, designer/server/src/models/forms/editor-v2/pages.test.js
Add missing flow 5:
Flow 5 – Display Question Listing Page
GIVEN I can see the Question overview page
AND I have finished configuring all the question pages I need
WHEN I select the back to all pages button
THEN the question listing page is displayed as per link whereby there is a row at the bottom of the summary list of said page called:
**People can answer More than once**
https://www.figma.com/design/1A9Tthy0CJeqp2rGNSKRjH/Defra-Form-Builder-flows?node-id=13384-96824&t=SkztKcLLhVb3YlXQ-4
=> Add repeater text to the pages overview

designer/client/src/javascripts/error-preview/error-preview.js, designer/client/src/javascripts/error-preview/error-preview.test.js, model/src/form/form-editor/index.ts, model/src/form/form-manager/types.ts
A fix following https://github.com/DEFRA/forms-designer/pull/871 to capitalise the first letter on the error descriptions:
=> fix 551320: capitalise first letter on error preview

designer/server/src/__stubs__/form-definition.js, model/src/conditions/migration.test.ts, model/src/conditions/migration.ts, model/src/form/form-definition/index.test.ts, model/src/form/form-definition/index.ts, model/src/form/form-definition/types.ts
Makes the referential integrity of conditions optional using `joi.when`.
`joi.string().uuid().required().when('/lists', { is: joi.exist(), then: joi.valid(joi.ref('/lists', { in: true })) })`
This approach will validate referential integrity of the data _only_ when the `/lists` are present at the root mean we don't have to maintain two copies of the same schema (the full one and a "payload" one")
Example
```
import joi from 'joi'
const list = joi.string().uuid().required()
const condition = joi
.object()
.keys({
list: joi
.string()
.uuid()
.required()
.when('/lists', { is: joi.exist(), then: joi.valid(joi.ref('/lists', { in: true })) }),
name: joi.string().required()
})
.required()
const def = joi
.object()
.keys({
lists: joi.array().items(list).required(),
conditions: …
```
=> Update conditions schema

designer/server/src/models/forms/editor-v2/base-settings-fields.js, designer/server/src/models/forms/editor-v2/base-settings-fields.test.js
When saving on the Autcomplete question page, if an error occurred (e.g. if a condition was linked ot his autocomplete), the autocomplete textarea value was not being restored correctly
=> Fixed autocomplete textarea value after error

designer/server/src/models/forms/editor-v2/condition-value.js, designer/server/src/models/forms/editor-v2/condition-value.test.js
Unnecessary extra logic removed to fix this bug.
Issue arose when 'period' was given a non-numeric value.
Typical screenshot of error shown below:
=> Fixes period field not erroring when given a non-numeric value

designer/server/src/__stubs__/form-definition.js, designer/server/src/lib/editor.test.js, designer/server/src/models/forms/editor-v2/page-conditions.js, designer/server/src/models/forms/editor-v2/page-conditions.test.js, designer/server/src/models/forms/editor-v2/pages.js, designer/server/src/models/forms/editor-v2/pages.test.js, designer/server/src/routes/forms/editor-v2/guidance.test.js, designer/server/src/views/forms/editor-v2/guidance.njk, designer/server/src/views/forms/editor-v2/page-conditions.njk, designer/server/src/views/forms/editor-v2/partials/conditions.njk, designer/server/src/views/forms/editor-v2/partials/guidance-left-panel.njk, designer/server/src/views/forms/editor-v2/partials/questions-left-panel.njk
Adds the condition tab (and conditions functionality) to the Guidance page
Ticket [DF-126](https://eaflood.atlassian.net/browse/DF-126)
[DF-126]: https://eaflood.atlassian.net/browse/DF-126?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Added conditions tab to guidance pages

designer/server/src/lib/condition-references.js, designer/server/src/lib/condition-references.test.js, designer/server/src/lib/editor.js, designer/server/src/lib/editor.test.js, designer/server/src/models/forms/editor-v2/condition-delete.js, designer/server/src/models/forms/editor-v2/condition-delete.test.js, designer/server/src/routes/forms/editor-v2/condition-delete.js, designer/server/src/routes/forms/editor-v2/condition-delete.test.js, designer/server/src/routes/forms/index.js
https://eaflood.atlassian.net/browse/DF-59?atlOrigin=eyJpIjoiOTkwMTA5MDI1MGI1NGQ5ODhlN2M3MzcxNzFmYzBlNjkiLCJwIjoiaiJ9
This PR introduces the ability to delete a condition whether assigned to a page or not. It also surfaces an error if the user attempts to delete a joined condition.
=> feat: delete condition page

model/src/utils/markdown.test.js, model/src/utils/markdown.ts
Handles external links when rendering markdown. Relies on a `baseUrl` parameter fed by the consumer. For use-cases where it's a bit complicated (e.g. designer where the hostname of the running service won't match the runner which renders the form), I've left it optional. This effectively means only runner will change.
=> Handle external links in markdown

designer/server/src/models/forms/editor-v2/check-answers-settings.js, designer/server/src/models/forms/editor-v2/conditions-join.js, designer/server/src/models/forms/editor-v2/conditions-join.test.js, designer/server/src/views/forms/editor-v2/conditions-join.njk
Bug [DF-324](https://eaflood.atlassian.net/browse/DF-324)
Wrong summary text for original condition when editing a joined condition
- Also fixed wrong preview link in Check Your Answers
[DF-324]: https://eaflood.atlassian.net/browse/DF-324?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Fixed joined condition original condition summary text

designer/server/src/lib/editor.js, designer/server/src/lib/editor.test.js, designer/server/src/models/forms/editor-v2/common.js, model/src/pages/helpers.ts, model/src/pages/index.ts
Bug [DF-288](https://eaflood.atlassian.net/browse/DF-288)
Sets appropriate controller type (or unsets if no longer needed)
- on add question
- on update question
- allows component type to be changed during edit of question, and correct controller gets set
- fixes a different bug where the incorrect question number was appearing when editing a question (when you had guidance on that page)
[DF-288]: https://eaflood.atlassian.net/browse/DF-288
=> Corrected controller logic DF-288

designer/server/src/__stubs__/form-definition.js, designer/server/src/routes/forms/editor-v2/helpers.js, designer/server/src/routes/forms/editor-v2/helpers.test.js, designer/server/src/routes/forms/editor-v2/questions.js, model/src/form/form-definition/index.ts
- Relax component name unique constraint by ignoring undefined. This will allow us to support multiple `ContentComponents` for plugin users.
- Make `name` field required for form components
=> DF-352: Fix guidance position during component reorder

.github/workflows/check-pull-request.yml
To fix vulnerability: https://community.sonarsource.com/t/security-advisory-sonarqube-scanner-github-action/147696
I could have opted to pin us to `v5.3.1` specifically but this gives us wiggle room for future changes, and as they follow semver this shouldn't be an issue.
=> Use sonarqube-scan-action v5

designer/server/src/plugins/errorPage.ts, package-lock.json, package.json
This should fix missing stack traces when an unhandled exception is encountered in a route handler.
[More info](https://discord.com/channels/1031830080109957162/1031830081242415106/threads/1423251797040042065)
---
Hi all 👋 
I'm looking for a way to capture and log stack traces when an unhandled exception is encountered in a route.
I have a generic onPreResponse handler for error logging that looks something like:
```
server.ext('onPreResponse', (request, h) => {
const response = request.response
if (Boom.isBoom(response)) {
// Stack trace is undefined for unhandled system errors
console.log(response.stack)
return h.response({}).code(500)
}
return h.continue
})
```
If I have a route that generates an unhandled error e.g.
```
{
method: 'GET',
path: '/generate-error',
async handler(request, …
```
=> fix/DF-531: Error stack traces
